package mindustryX.bundles

import arc.struct.ObjectMap
import java.io.StringReader
import java.util.Properties

/**
 * Embedded MDTX bundle data migrated from assets/bundles.
 */
object MdtxBundleData {
    val zh: ObjectMap<String, String> by lazy { parse(ZH_PROPERTIES) }
    val en: ObjectMap<String, String> by lazy { parse(EN_PROPERTIES) }

    private fun parse(text: String): ObjectMap<String, String> {
        val properties = Properties()
        StringReader(text).use { properties.load(it) }

        val map = ObjectMap<String, String>(properties.size)
        for ((key, value) in properties) {
            map.put(key.toString(), value.toString())
        }
        return map
    }

    private val ZH_PROPERTIES = """
|#UI
|mods.group.mod = 模组
|mods.group.internal = 内置模组
|mods.disabled = 禁用Mod
|
|mods.recommend = [accent]MdtX[]推荐辅助模组列表
|mods.recommend.lastUpdated = 推荐列表更新时间：{0}
|mods.recommend.info = 精选辅助模组
|mods.recommend.mod.description = 精选推荐模组
|mods.recommend.mod.name = 模组：{0}
|mods.recommend.mod.author = 作者：{0}
|mods.recommend.mod.minGameVersion = 最低支持游戏版本：{0}
|mods.recommend.mod.lastUpdated = 上次更新时间：{0}
|mods.recommend.mod.stars = Github收藏数：{0}
|
|alphaLoading = {jump}[gray]加载中...
|alphaLoadFailed = {sick}[gray]加载失败...
|
|contentSelector = 选择内容
|mdtx.report = 问题反馈
|mdtx.qqLink = QQ交流群
|
|mdtx.share.item = {0}：库存 {1}，产量 {2}/秒
|mdtx.share.unit = {0}：数量 {1}，上限 {2}
|
|commit.recentUpdates = 近期更新
|commit.title = 提交记录
|
|overlayUI.tips = [gold]Tips:[]\n1. PC默认快捷键为Z，可在设置中修改。\n2. 面板锁定后可在游戏内显示。\n3. 并非所有面板需要锁定，左侧开关可当作折叠按钮。\n4. 面板锁定后内容区域保持不变，吸附会自动跟随。\n5. 手机可在窗口设置里面调整缩放，信息展示可以缩写，按钮可以放大。
|forceJoin.tips = [gold]MDTX[]: 目标版本可能兼容，你可以选择伪装版本强制加入。\n如果出现[red]网络错误[]或其他问题，表示无法兼容。\n\nTIPS: 向下兼容(v146-当前版本)是MDTX独有特性哦。
|#end UI
|
|status.slow.name = 缓慢
|status.shielded.name = 保护
|status.corroded.name = 腐蚀
|status.disarmed.name = 缴械
|status.invincible.name = 无敌
|status.fast.name = 迅捷
|
|#StatExt
|category.combat = 战斗
|category.moreContent.name = 更多内容适配
|category.movement = 移动
|category.support = 支援
|
|stat.can_overdrive = 能否超速
|stat.cost = 建造时间花费
|stat.health_scaling = 建筑血量系数
|stat.hardness = 硬度
|stat.buildable = 是否用于建造
|stat.boil_point = 沸点
|stat.drag_multiplier = 移动阻力倍率
|
|stat.buffer_capacity = 缓存容量
|stat.regen_speed = 回复速度
|stat.mend = 修复量
|stat.mend_reload = 修复间隔
|stat.mend_speed = 修复速度
|stat.warmup_partial = 启动时间
|stat.warmup_time = 完全启动时间
|stat.warmup_power = 启动总耗电
|
|stat.rotate_speed = 转向速度
|stat.boost_multiplier = 助推速度倍率
|stat.drown_time_multiplier = 淹没时间倍率
|stat.mine_level = 采矿等级
|
|stat.estimate_dps = 预估dps
|stat.ai_controller = 默认AI
|stat.targets = 目标
|stat.ammo_type = 子弹类型
|stat.ammo_capacity = 子弹容量
|
|#end StatExt
|
|#SettingsV2
|settings.category.settingV2 = [gold]MindustryX
|settingV2.reset = [red]恢复默认设置
|settingV2.onlyModified = 只看已修改的设置
|
|settingV2.autoFill.category = 快速装填
|settingV2.autoFill.cooldown.name = 操作冷却(ms)
|settingV2.autoFill.cooldown.description = 过小的值可能导致被服务器踢出
|settingV2.autoFill.minFill.name = 最小装填个数
|settingV2.autoFill.fillStorageBlock.name = 允许往容器/仓库内填充
|settingV2.autoFill.fillDistribution.name = 允许往塑钢/桥中填充
|
|settingV2.coreItems.category = 队伍资源显示
|settingV2.coreItems.showItem.name = 显示核心物品
|settingV2.coreItems.showUnit.name = 显示单位数量
|settingV2.coreItems.showPlan.name = 显示建筑中数量
|settingV2.coreItems.showPower.name = 显示电网信息
|setting.coreitems.name = 显示核心物资(已弃用，请在V2设置中修改)
|
|settingV2.AutoUpdate.category = 自动更新
|settingV2.AutoUpdate.showUpdateDialog.name = 检测到新版本提示
|settingV2.AutoUpdate.ignoreOnce.name = 跳过当前版本
|settingV2.AutoUpdate.ignoreUntil.name = 7天不再提示
|
|settingV2.quickButtons.category = 快捷按钮
|settingV2.quickButtons.columns.name = 快捷按钮列数(每行个数)
|settingV2.quickButtons.customButtons.name = 自定义指令
|
|settingV2.damagePopup.category = 血量跳字(伤害跳字)
|settingV2.damagePopup.enable.name = 开启血量跳字显示
|settingV2.damagePopup.playerOnly.name = 仅玩家自己的(包括控制的)
|settingV2.damagePopup.showHeal.name = 回血跳字[grey](否则只显示伤害)
|settingV2.damagePopup.minHealth.name = 最低血量限制
|
|settingV2.entityRender.category = 实体渲染相关
|settingV2.entityRender.unitHide.name = 隐藏单位
|settingV2.entityRender.unitHideExcludePlayers.name = 始终显示玩家单位
|settingV2.entityRender.unitHideMinHealth.name = 隐藏低于指定血量单位
|settingV2.entityRender.noBulletShow.name = 隐藏子弹[grey]显著降低渲染(DW)开销
|settingV2.entityRender.unitHitbox.name = 显示单位碰撞箱
|settingV2.entityRender.payloadPreview.name = 载荷拾起预览
|
|settingV2.gameUI.category = 游戏界面
|settingV2.gameUI.spawnerWaveDisplay.name = 出生点波次信息显示
|settingV2.gameUI.transportScan.name = 物流扫描模式
|settingV2.gameUI.menuFloatText.name = 首页浮动标语
|settingV2.gameUI.announceRtsTake.name = 当其他人分走当前控制的单位时，消息提示
|settingV2.gameUI.deadOverlay.name = 死亡时(观战)仍然显示界面 [orange]可能闪退
|settingV2.gameUI.deadOverlay.description = 观战时仍然显示界面，方便查看信息，复制蓝图
|settingV2.gameUI.invertMapClick.name = 反转小地图的左右键点击
|settingV2.gameUI.invertMapClick.description = 反转后：左键拖动，右键打开
|settingV2.gameUI.arcSpecificTable.name = 左上角学术特制信息显示(停止维护)[orange][重启生效]
|settingV2.gameUI.itemSelectionHeight.name = 建筑选择框(右下角)行数
|settingV2.gameUI.itemSelectionWidth.name = 建筑选择框(右下角)列数
|settingV2.gameUI.researchViewer.name = 科技树透视器
|settingV2.gameUI.extendedCommandTable.name = RTS扩展按钮
|settingV2.gameUI.overlayButton.name = OverlayUI按钮[grey]推荐PC使用快捷键Z
|
|settingV2.additionInventoryColumns.name = 更宽的选择栏(额外列数)
|settingV2.additionInventoryColumns.description = 涉及核心物品栏、建筑物品栏与物品配置栏、编辑器方块栏等
|settingV2.minimapSize.name = 小地图大小
|settingV2.staticShieldsBorder.name = 静止力墙边界
|settingV2.allUnlocked.name = 显示所有内容(含隐藏)
|settingV2.noPlayerHitBox.name = 取消玩家自身的碰撞 [gray]轻微作弊
|settingV2.arcTurretPlaceCheck.name = 炮台放置时显示禁建范围
|settingV2.arcTurretPlacementItem.name = 炮台显示不同弹药射程
|settingV2.githubMirror.name = GitHub镜像加速(WZ镜像)
|settingV2.githubMirror.description = 优化全球服务器列表及Mod浏览器功能
|settingV2.replayRecord.name = 多人游戏录像
|settingV2.replayRecord.description = 自动录制游玩过程，输出在saves文件夹\n录像文件较大，记得整理
|settingV2.maxSchematicSize.name = 最大选择框(蓝图)大小
|settingV2.autoSelectSchematic.name = 蓝图自动选择      [gray]打开蓝图时自动筛选
|settingV2.collectMetrics.name = 匿名信息采集
|settingV2.collectMetrics.description = 匿名采集崩溃日记/运行环境等信息\n帮助开发者改进游戏
|settingV2.worldCreator.name = 创世神
|settingV2.worldCreator.description = 无视限制，能够放置、拆除任何方块
|settingV2.terrainSchematic.name = 地形蓝图
|settingV2.terrainSchematic.description = 允许复制地形、墙体等到蓝图中，可配合创世神粘贴。
|
|settingV2.arcExtra.category = ARC-扩展功能
|settingV2.arcExtra.colorizedContent.name = 使用彩色物品名字[grey]可读性可能下降
|settingV2.arcExtra.backgroundPath.name = 首页-自定义背景
|settingV2.arcExtra.backgroundPath.description = 需要填写完整路径
|settingV2.arcExtra.radarMode.name = 雷达扫描速度
|settingV2.arcExtra.radarSize.name = 雷达大小
|settingV2.arcExtra.schematicShare.name = 接收蓝图分享
|
|settingV2.block.category = 建筑相关设置
|settingV2.block.rotateCanvas.name = 蓝图旋转时会旋转画板内容 [orange]可能导致崩溃，小心使用
|settingV2.block.arcChoiceUiIcon.name = 显示装卸|分类的物品图标
|settingV2.block.hiddenItemTransparency.name = 带桥/交叉器内物品的不透明度
|settingV2.block.overdriveZoneTransparency.name = 超速范围的不透明度
|settingV2.block.mendZoneTransparency.name = 修复范围的不透明度
|settingV2.block.healthBarMinHealth.name = 建筑血量显示最低血量
|settingV2.block.renderLevel.name = 建筑渲染等级
|settingV2.block.showOtherTeamState.name = 查看其他队伍建筑状态(只读)
|settingV2.block.editOtherBlock.name = 编辑其他队伍建筑     [yellow][限单机,作弊功能]
|settingV2.block.logicDisplayNoBorder.name = 去除显示屏边框
|settingV2.block.arcPlacementEffect.name = 建筑放置特效
|
|settingV2.logicSupport.category = 逻辑辅助器
|settingV2.logicSupport.visible.name = 编辑器显示逻辑辅助
|settingV2.logicSupport.changeSplash.name = 变量变动闪烁
|settingV2.logicSupport.memoryColumns.name = 内存元显示列数
|settingV2.logicSupport.memoryDecimal.name = 内存元显示精度
|
|settingV2.overlayUI.category = Overlay UI
|settingV2.overlayUI.debug.name = Debug面板
|settingV2.overlayUI.auxiliaryTools.name = 辅助按钮
|settingV2.overlayUI.quickTool.name = 快速设置
|settingV2.overlayUI.mappingTool.name = 作图工具箱
|settingV2.overlayUI.advanceBuildTool.name = 批量建筑工具
|settingV2.overlayUI.teamsStats.name = 多队伍资源显示
|settingV2.overlayUI.coreItems.name = 队伍资源显示
|settingV2.overlayUI.waveInfo.name = 新波次信息显示
|settingV2.overlayUI.controlGroup.name = RTS编组面板
|settingV2.overlayUI.markAndShare.name = 标记与分享
|
|settingV2.debug.category = 特殊设置(不保证稳定性)
|settingV2.debug.renderSort.name = 渲染排序
|settingV2.debug.renderSort.description = 渲染过程根据贴图排序\n多图集(Mod较多)情况下能够提升50%渲染性能，但可能造成渲染错误
|settingV2.debug.reliableSync.name = 使用TCP发送全部数据包
|settingV2.debug.limitUpdate.name = 限制更新
|settingV2.debug.limitUpdate.description = 此功能可以大幅减少LG开销，但会导致视角外的一切停止运算\n强烈不建议在单人开启，在服务器里会造成不同步
|#end SettingsV2
|
|# Binding
|keybind.arcDetail.name = 雷达扫描
|keybind.arcScanMode.name = 扫描详情
|keybind.oreAdsorption.name = 矿物自动吸附
|keybind.showRTSAi.name = 显示单位控制
|keybind.superUnitEffect.name = 显示玩家射程
|keybind.overlayUI.name = 开关OverlayUI
|# end Binding
|
|# editor增强
|toolmode.square2 = 方形(直径)
|toolmode.square2.description = 同方形。但大小为直径(延续学术功能)
|#end editor增强
|
|bar.reloadDetail = 装填：{0}%
|bar.warmupDetail = 充能：{0}%
|bar.ammoDetail = 弹药：{0}/{1}
|
|
|marker.Mark.name = 标记
|marker.Gather.name = 集合
|marker.Attack.name = 攻击
|marker.Defend.name = 防御
|marker.What.name = 问号
|
|keybind.point.name = 标记
|keybind.lockonLastMark.name = 定位到上个标记点
|keybind.toggle_block_render.name = 切换建筑显示
|keybind.toggle_unit.name = 切换单位显示
|keybind.focusLogicController.name = 锁定当前控制的处理器
|keybind.placeRouterReplacement.name = 传送带快速替换(路由器/桥)
|
|
|# ARC设置
|category.arcAddTurretInfo.name = 更多炮台属性
|category.arcAddUnitInfo.name = 更多单位属性
|category.arcCDisplayBlock.name = 建筑显示
|category.arcCGraphicsOther.name = 其他
|category.arcCOverview.name = 全局设置
|category.arcCgameview.name = 游戏画面
|category.arcCgamewindow.name = 游戏界面
|category.arcMassDriverInfo.name = 质驱引导线
|category.arcPlayerEffect.name = 玩家炫酷特效
|category.arcWeakCheat.name = 弱作弊功能
|
|setting.alwaysShowUnitRTSAi.name = 单位：执行的RTS命令
|setting.arcAlwaysTeamColor.name = 玩家列表：总是绘制队伍颜色
|setting.arcBuildInfo.name = [cyan]建造范围
|setting.arcdrillmode.name = 钻头：常亮矿物
|setting.blockBars.name = 建筑属性
|setting.blockBars_mend.name = 修复：进度条
|setting.blockWeaponTargetLine.name = 炮台：瞄准线
|setting.blockWeaponTargetLineWhenIdle.name = 炮台：瞄准线（闲置）
|setting.blockdisabled.name = 常显建筑禁用状态
|setting.hoveredTileInfo.name = 显示鼠标指针地块/建筑名称
|setting.mass_driver_line.name = 显示质驱引导线
|setting.mass_driver_line_color.name = [pink]质驱引导线：颜色
|setting.mass_driver_line_interval.name = 质驱引导线：箭头间隔
|setting.overrideSkipWave.name = 功能：忽视跳波限制
|setting.playerEffectColor.name = 玩家射程：颜色
|setting.playerEffectCurStroke.name = 玩家射程：粗细
|setting.playerNeedShooting.name = [red]时间管理大师
|setting.rtsWoundUnit.name = 单位筛选：残血阈值
|setting.save_more_map.name = 保存战役与编辑器地图
|setting.showTurretAmmo.name = 炮台：子弹类型
|setting.showTurretAmmoAmount.name = 炮台：子弹数量
|setting.superUnitEffect.name = [pink]玩家特效射程
|setting.turretAlertRange.name = 炮台：警告范围
|setting.turretForceShowRange.name = 炮台：强制显示射程  [gray]可用于在编辑器下显示射程
|setting.turretShowRange.name = 炮台：射程
|setting.unitHealthBar.name = 单位属性
|setting.unitItemCarried.name = 单位携带的物品
|setting.unitLogicMoveLine.name = 控制：移动路径
|setting.unitLogicTimerBars.name = 控制：时间条
|setting.unitTargetType.name = [pink]玩家的目标风格
|setting.unitWeaponRange.name = 单位武器射程：范围警告
|setting.unitWeaponRangeAlpha.name = 单位武器射程：不透明度
|setting.unitWeaponTargetLine.name = 单位武器目标
|setting.unitbuildplan.name = 单位：建造序列显示
|settings.arc = 学术功能
|
|# ARC增加
|bar.drillcantmine = 当前钻头不能挖掘此矿物
|revealedblocks = 显示建筑
|rules.aiCoreSpawn = 核心生成AI
|rules.canGameOver = 能否自动结束游戏[gray](如果没有其他结束游戏的方法，不推荐开启)
|rules.cheat = 作弊模式(无限火力)
|rules.coreDestroyClear = 核心被破坏清理附近建筑
|rules.disableOutsideArea = 禁用场外区域
|rules.dynamicColor = 战争迷雾颜色-已探索区域[gold]X[]
|rules.infiniteAmmo = 单位无限子弹 [gray](不建议关闭)
|rules.staticColor = 战争迷雾颜色-未探索区域[gold]X[]
|rules.title.arcExperimental = 隐藏设置[red](实验性功能，可能影响稳定性)
|rules.unitPayloadUpdate = 单位携带的方块会工作
|rules.winWave = 胜利波次[gold]X[]  [gray](到达指定波次后自动停止)
|schematic.preview = 预览
|settings.maxMsgRecorded.name = 最大聊天记录数
|shield.phaseboost = [stat]+{0}[lightgray] 格 [stat]+{1}[] 护盾容量
|shield.regenspeed = [stat]{0}[lightgray]x 回复速度
|
|# 原版额外内容
|content.planet.name = 星球
|content.weather.name = 天气
|unit.anthicus-missile.name = 天灾导弹
|unit.disrupt-missile.name = 悲怆导弹
|unit.quell-missile.name = 遏止导弹
|unit.scathe-missile.name = 创伤导弹
|team.neoplastic.name = 瘤
|
|# 学术特色翻译(无需翻译其他语言)
|ability.energyfield.maxtargets = [lightgray]最大目标: [white]{0}
|ability.energyfield.sametypehealmultiplier = [lightgray]同类回复: [white]{0}%
|bar.drilltierreq = 需要{0}级的钻头(当前{1}级)
|block.armored-duct.name = 装甲运输管
|block.large-shield-projector.name = 大型护盾投影
|rules.waitForWaveToEnd = 等待波次结束[gray]所有敌人死亡后才会开始下一波次
|schematic.tagged = {0} 个带标签的蓝图
|unit.incite.name = 策动(激发)
|unit.obviate.name = 消散(影逝)
|unit.quell.name = 遏止(终结)
|unit.disrupt.name = 悲怆(瓦解)
|ability.liquidregen = 液体回血
|
|# 临时中文翻译(无需翻译其他语言)
|database.patched = 已被内容包修改
|rules.logicunitbuild = 允许逻辑控制单位建造
|mdtx.rules.possessionAllowed = 允许控制单位
|mdtx.rules.disableRebuild = 禁用重建
|mdtx.rules.enableInfiniteAmmoAll = 所有队伍开启无限火力
|mdtx.rules.disableInfiniteAmmoAll = 所有队伍关闭无限火力
|mdtx.rules.moreTeamOptions = 更多队伍设置
|mdtx.rules.moreTeamSelect = 更多队伍选择
|mdtx.rules.customBackground = 自定义背景[lightgray](需要设置空地板)
|mdtx.rules.bgZoom = 放缩
|mdtx.rules.bgPosX = 位置x
|mdtx.rules.bgPosY = 位置y
|mdtx.rules.bgPosZ = 位置z
|mdtx.waves.toggleDisplayMode = 切换显示模式
|mdtx.editor.centerHint = 右键画笔图标以及其他图标弹出的高级绘制选项是X端特有功能哦\nRight-click the brush icon and other icons to open advanced drawing options; this is a MindustryX-only feature.
|mdtx.editor.otherTeams = [violet]其他队伍
|mdtx.editor.grid = 辅助线：
|mdtx.editor.brush = 笔刷：
|mdtx.waves.legend = \uE86D 单位数量；\uE813 单位血+盾；\uE810 buff后血+盾；\uE86E 预估DPS
|mdtx.waves.waveIndex = 第[accent]{0}[]波
|mdtx.waves.noEnemies = 该波次没有敌人
|mdtx.waves.loadMore = 加载更多波次
|mdtx.waves.carryItem = 携带物品[gold]X[]:
|mdtx.waves.carryItemDenied = [red]该单位不可携带物品
|mdtx.waves.carryPayload = 携带载荷[gold]X[]:
|mdtx.waves.carryPayloadDenied = [red]该单位不可携带载荷
|mdtx.logic.convertFailed = [orange]警告：转换失败，请输入正确格式
|mdtx.logic.discardChanges = [orange]丢弃更改
|mdtx.logic.confirmDiscard = 确认丢弃?
|mdtx.logic.jumpLine = [gold]跳转行号:[] {0}
|mdtx.unit.payload = 装载：{0}/{1} {2}
|mdtx.unit.stat.hp = 血量
|mdtx.unit.stat.dmg = 伤害
|mdtx.unit.stat.rld = 攻速
|mdtx.unit.stat.spd = 移速
|mdtx.unit.stat.bld = 建速
|mdtx.unit.stat.drag = 阻力
|mdtx.unit.stat.arm = 装甲
|mdtx.unit.mineLevelFormat = @级
|mdtx.weapon.range = [lightgray]武器范围: [stat]{0}[]格
|mdtx.weapon.rotateSpeed = [lightgray]旋转速度: [stat]{0}[]°/s
|mdtx.weapon.rotateLimit = [lightgray]旋转范围: [stat]{0}[] {1}
|mdtx.content.shareBrief = ♐简
|mdtx.content.shareDetail = ♐详
|mdtx.database.unlock = 解禁
|mdtx.forceJoin.join = 强制加入
|mdtx.keybind.unbind = 取消绑定
|mdtx.planet.sectorName = 区块名称
|mdtx.research.prereqMissing = [red]未满足前置科技
|mdtx.research.prereqLine = {0}\n[red]未满足前置科技
|mdtx.schematics.archive = 蓝图档案馆
|mdtx.schematics.converter = 图片转换器
|mdtx.schematics.converterWithIcons = 图片转换器{0}{1}{2}
|mdtx.schematics.techTree = 科技树：
|mdtx.schematics.assistFilter = 辅助筛选：
|mdtx.schematics.canBuildTip = 可建造(核心有此类资源+地图未禁用)
|mdtx.schematics.contains = 蓝图包含：
|mdtx.schematics.mustContainTip = 蓝图需包含此建筑
|mdtx.schematics.filterMode = [orange]蓝图筛选模式[white]:蓝图必须包含 {0}
|mdtx.schematics.shareChat = 聊天分享蓝图
|mdtx.schematics.copyAdvanced = 复制到剪贴板(含介绍)
|mdtx.schematics.fromServer = 来自服务器的蓝图
|mdtx.schematics.fromPlayer = 来自{0}的蓝图
|mdtx.schematics.autoTag = 自动标签
|mdtx.schematics.logicCopied = 已复制逻辑代码
|mdtx.hud.enterMarkMode = 进入标记模式
|mdtx.hud.teamPrefix = 前缀添加/t
|mdtx.hud.lockLastMark = 锁定上个标记点
|mdtx.hud.more = 更多
|mdtx.hud.scale = 缩放: {0}
|mdtx.hud.enemyCores = 敌人核心：[orange]{0}
|mdtx.hud.wave = 波次：[orange]{0}
|mdtx.rts.highHealth = 高血量单位
|mdtx.rts.lowHealth = 低血量单位
|mdtx.rts.attackUnit = 进攻性单位
|mdtx.rts.supportUnit = 辅助性单位
|mdtx.rts.airUnit = 飞行单位
|mdtx.rts.landUnit = 陆军单位
|mdtx.rts.navalUnit = 海军单位
|mdtx.rts.select = RTS控制器：选择{0}！
|mdtx.rts.remove = RTS控制器：移除{0}！
|mdtx.player.copiedName = 已复制昵称：{0}
|mdtx.bar.charge = 充能: {0} / {1}
|mdtx.bar.boost = 超速：{0}
|mdtx.bar.drillSpeed = 挖掘速度：{0}{1}/s
|mdtx.apk.installFailed = 安装APK失败
|mdtx.stat.buildingDamage = {0}[lightgray]x建筑伤害
|mdtx.stat.range = [lightgray]射程 {0} [lightgray]格
|mdtx.stat.reloadRate = {0}[lightgray]x射速
|mdtx.stat.pierceFalloff = {0}%衰减
|mdtx.stat.pierceUnlimited = 无限
|mdtx.stat.pierceTimes = {0}x
|mdtx.stat.pierceLabel = 穿透[lightgray]
|mdtx.stat.pierceBoth = 建筑与单位
|mdtx.stat.pierceBuilding = 建筑
|mdtx.stat.pierceUnit = 单位
|mdtx.stat.pierceElectric = [stat](电性)
|mdtx.stat.pierce = {0}穿透[lightgray]{1}{2}
|mdtx.stat.homing = [stat]追踪[lightgray]~[]{0}°/s[lightgray]~[]{1}[lightgray]格
|mdtx.stat.emp.summary = [stat]EMP~{0}[lightgray]格[]~[white]\uE810[]{1}%/[white]\uE86D[]{2}%~[white]\uF899[][green]{3}%[]/[negstat]{4}%[]
|mdtx.stat.emp.powerDamage = [stat]对敌方电网建筑造成{0}%子弹伤害
|mdtx.stat.emp.unitDamage = [stat]对敌方单位造成{0}%子弹伤害
|mdtx.stat.emp.allyBoost = [stat]对我方耗电建筑超速至{0}%
|mdtx.stat.emp.enemySlow = [stat]对敌方电网建筑减速至{0}%
|mdtx.stat.lightningDamage = 闪电~[stat]{0}[]伤害~
|mdtx.stat.lightningLengthRange = [stat]{0}~{1}[]长度
|mdtx.stat.lightningLength = [stat]{0}[]长度
|
|
|
|# hardcoded ui texts extracted from source
|mdtx.ui.empty_selection_area_hint = 当前选定区域为空，请通过F规划区域
|mdtx.ui.sync_a_wave = 同步一波
|mdtx.ui.miner_ai_ore_filter = minerAI-矿物筛选器
|mdtx.ui.blueprint_code_n = 蓝图代码：\n
|mdtx.ui.copied_print_buffer_n_arg = 复制信息版\n@
|mdtx.ui.message_center = 中央监控室
|mdtx.ui.lock = 锁定
|mdtx.ui.event_map_load = 事件~载入地图
|mdtx.ui.logic_helper_x = 逻辑辅助器[gold]X[]
|mdtx.ui.surrender_vote_confirm = 受不了，直接投降？
|mdtx.ui.shortcut_observer_mode = 观
|mdtx.ui.original_size = 原始大小
|mdtx.ui.current_unit_cannot_build = [red]当前单位不可建筑
|mdtx.ui.unit = 单位：
|mdtx.ui.zoom = 缩放
|mdtx.ui.add_prefix_t = 前缀添加/t
|mdtx.ui.observer_mode = 观察者模式
|mdtx.ui.shortcut_unit_render = 兵
|mdtx.ui.export = 导出
|mdtx.ui.air_only = 仅对空
|mdtx.ui.logic_notice = 逻辑~通报
|mdtx.ui.share_wave_information = 分享波次信息
|mdtx.ui.name = 名称
|mdtx.ui.wave_in_prefix = 还有
|mdtx.ui.warning_image_may_be_too_large_please_try_compressing_image = [orange]警告：图片可能过大，请尝试压缩图片
|mdtx.ui.all_players = 全部玩家
|mdtx.ui.icon = 图标
|mdtx.ui.bullet_rendering = 子弹显示
|mdtx.ui.failed_to_read_image_please_try_another_image_n = 读取图片失败，请尝试更换图片\n
|mdtx.ui.mark_player = 标记~玩家
|mdtx.ui.chat_history_exceeding_the_limit_will_be_cleared_when_loading_the_map = 超出限制的聊天记录将在载入地图时清除
|mdtx.ui.wave = 波
|mdtx.ui.player_name = 玩家名:
|mdtx.ui.randomly_generated_within_this_range_near_the_target_point = 在目标点附近的这个范围内随机生成
|mdtx.ui.on = 开启
|mdtx.ui.slow_the_flow_of_time_to_half = 将时间流速放慢到一半
|mdtx.ui.ore_info = 矿物信息
|mdtx.ui.shortcut_fog = 雾
|mdtx.ui.check_for_updates = 自动更新
|mdtx.ui.always_on = 一直开启
|mdtx.ui.exported_in_game_chat_history = ] 导出的游戏内聊天记录
|mdtx.ui.allowed_range_2_9999 = 允许的范围：2~9999
|mdtx.ui.clear_all_core_resources = 清空核心的所有资源
|mdtx.ui.arc_image_converter = arc-图片转换器
|mdtx.ui.artboard = 画板++
|mdtx.ui.radar_toggle = 雷达开关
|mdtx.ui.current_map_name = *** 当前地图名称:
|mdtx.ui.ui_toolkit = ui大全
|mdtx.ui.ring_cross = 圆十字
|mdtx.ui.please_don_t_tag_too_often = 请不要频繁标记!
|mdtx.ui.message_arg_js_starts_with_script = 消息(@js 开头为脚本)
|mdtx.ui.mark_map_location = 标记地图位置
|mdtx.ui.temporary_status = <瞬间状态>
|mdtx.ui.blueprint_name = 蓝图名：
|mdtx.ui.unit_factory_x = 单位工厂-X
|mdtx.ui.the_blueprint_code_is_too_long_please_click_the_link_to_view_it = 蓝图代码过长，请点击链接查看
|mdtx.ui.ground_only = 仅对地
|mdtx.ui.flash_on_change = 变动闪烁
|mdtx.ui.show_all = 全部显示
|mdtx.ui.reset = 重置
|mdtx.ui.shortcut_server_info = 版
|mdtx.ui.shield = [yellow]护盾：
|mdtx.ui.spawn_range = 生成范围：
|mdtx.ui.click_the_screen_to_return = [green]点击屏幕返回
|mdtx.ui.team_id = 队伍ID:
|mdtx.ui.refresh_interval = 刷新间隔
|mdtx.ui.export_chat_history = 导出聊天记录
|mdtx.ui.scan_mode = 扫描模式
|mdtx.ui.arc_ai_configurator = ARC-AI设定器
|mdtx.ui.resistance = [purple]阻力
|mdtx.ui.load_unit = 装载单位
|mdtx.ui.unit_factory = 单位工厂
|mdtx.ui.tiles = 格
|mdtx.ui.zoom_zoom = 缩放: 
|mdtx.ui.automatically_refresh_variables = 自动刷新变量
|mdtx.ui.fog_of_war = 战争迷雾
|mdtx.ui.maximum_storage_of_chat_history_too_high_may_cause_lag = 最大储存聊天记录(过高可能导致卡顿)：
|mdtx.ui.show_all_message_blocks = 信息板全显示
|mdtx.ui.attack_no_border = 攻击去边框
|mdtx.ui.arg_shield_capacity_arg_grid_arg_recovery_arg_s_cooldown = @盾容~@格~@恢复~@s冷却
|mdtx.ui.staging_area = 暂存区
|mdtx.ui.there_are_no_enemies_in_this_wave = 该波次没有敌人
|mdtx.ui.shortcut_surrender_vote = [white]法
|mdtx.ui.construction_suspended = 暂停建造
|mdtx.ui.waves = 波次：
|mdtx.ui.hide_all_buildings = 隐藏全部建筑
|mdtx.ui.cancel = 取消
|mdtx.ui.preview_releases_n_faster_updates_new_features_bug_fixes = 预览版(更新更快,新功能体验,BUG修复)
|mdtx.ui.open_playback_file = 打开回放文件
|mdtx.ui.copied_successfully = 复制成功:
|mdtx.ui.minimap = 小地图显示
|mdtx.ui.sandbox = 沙盒
|mdtx.ui.build_speed = [accent]建速
|mdtx.ui.recording_ended = 录制结束
|mdtx.ui.chat = 聊天
|mdtx.ui.team_range = 队伍区域
|mdtx.ui.wave_info = 波次信息
|mdtx.ui.defender_ai = 保护AI
|mdtx.ui.recording_error = 录制出错!
|mdtx.ui.show_building_status_only = 只显示建筑状态
|mdtx.ui.current_game_speed_arg_times = 当前游戏速度：@倍
|mdtx.ui.pause_logic_game_execution = 暂停逻辑(游戏)运行
|mdtx.ui.return_to_original_speed = 恢复原速
|mdtx.ui.air_x = ,空x
|mdtx.ui.flight_mode = 飞行模式
|mdtx.ui.automatically_save_as_blueprint = 自动保存为蓝图
|mdtx.ui.built_in_prefix = [内置]
|mdtx.ui.item = 物品
|mdtx.ui.speed_up_time_to_2x = 将时间流速加快到两倍
|mdtx.ui.enter_the_conveyor_belt = 进入传送带
|mdtx.ui.blueprint_cost = 蓝图造价：
|mdtx.ui.scaled_size = 缩放后大小
|mdtx.ui.mark_coordinates = 标记~坐标
|mdtx.ui.tip_all_schematics_containing_processors = TIP: 所有包含处理器的蓝图
|mdtx.ui.shortcut_wall_shadow = 墙
|mdtx.ui.panels_currently_unavailable = 当前不可用的面板:
|mdtx.ui.select_and_import_pictures_which_can_be_converted = 选择并导入图片，可将其转成画板、像素画或是逻辑画
|mdtx.ui.stable_releases = 正式版
|mdtx.ui.more_teams = 更多队伍选择
|mdtx.ui.set_target = 设置目标
|mdtx.ui.movement_speed = [cyan]移速
|mdtx.ui.frame_rate_lock_mode_enabled_ncurrent_frame_rate_lock_arg = 已开启帧率锁定模式\n当前帧率锁定：@
|mdtx.ui.server_ip = 服务器ip:
|mdtx.ui.current_selection_is_empty_select_a_block_in_the_inventory = [yellow]当前选中物品为空，请在物品栏选中建筑
|mdtx.ui.off = 关闭
|mdtx.ui.shortcut_message_center = 信
|mdtx.ui.index = 序号
|mdtx.ui.current_map_arg = 当前地图:@
|mdtx.ui.release_notes = 发布说明
|mdtx.ui.clone = 克隆
|mdtx.ui.saved_to_clipboard = 已保存至剪贴板
|mdtx.ui.recording_arg = 录制中: @
|mdtx.ui.there_are_too_many_buildings_to_avoid_lag_and_only_keep_the_first_1000_plans = [yellow]建筑过多，避免卡顿，仅保留前1000个规划
|mdtx.ui.load_building = 装载建筑
|mdtx.ui.generated_label = [orange]已
|mdtx.ui.canvas = 画板
|mdtx.ui.unlimited = 无限制
|mdtx.ui.buildings = 建筑：
|mdtx.ui.auto_attack = 自动攻击
|mdtx.ui.playback_length = 回放长度:
|mdtx.ui.liquids = 液体
|mdtx.ui.all = 全部
|mdtx.ui.replay_stats = 回放统计
|mdtx.ui.hp = [acid]血量
|mdtx.ui.pause_time = 暂停时间
|mdtx.ui.restore_current_wave = 恢复当前波次
|mdtx.ui.arg_arg_ndistance_arg = @,@\n距离: @
|mdtx.ui.successfully_selected_a_total_of = 成功选取共
|mdtx.ui.pixel_art = 像素画
|mdtx.ui.terrain_blueprint = 地形蓝图
|mdtx.ui.each_cell_absorbs_arg_s_arg_arg_arg_s_and_returns_blood_maximum_arg_s = 每格吸收@/s@@~@/s回血~最大@/s
|mdtx.ui.attack_speed = [violet]攻速
|mdtx.ui.toggle_your_team_s_cheat = 开关自己队的无限火力
|mdtx.ui.generate_quantity = 生成数量:
|mdtx.ui.unique = 独一无二
|mdtx.ui.drop_payload = 丢下载荷
|mdtx.ui.clear = 清空
|mdtx.ui.reset_all_links = 重置所有链接
|mdtx.ui.editor = 编辑器
|mdtx.ui.attack = 攻击
|mdtx.ui.select_image_png = 选择图片[white](png)
|mdtx.ui.hitbox_overlay = 碰撞箱显示
|mdtx.ui.logic_announcement = 逻辑~公告
|mdtx.ui.team = 队伍：
|mdtx.ui.self_destruct = 自杀
|mdtx.ui.copied_variable_name_n_arg = 复制变量名\n@
|mdtx.ui.ore_count_surface_wall = 矿物矿(地表/墙矿)
|mdtx.ui.you_are_already_on_the_latest_version = 你已是最新版本，不需要更新！
|mdtx.ui.hue_mode = 色调函数:
|mdtx.ui.load_self = 装载自己
|mdtx.ui.auto_fill = 一键装填
|mdtx.ui.arc_ore_statistics = ARC-矿物统计
|mdtx.ui.extract_code_from_schematic = 从蓝图中选择代码
|mdtx.ui.shortcut_bullet_render = 弹
|mdtx.ui.fixed_size = 固定大小
|mdtx.ui.command = 指令
|mdtx.ui.color = 颜色
|mdtx.ui.flash_on_variable_change = 变量变动闪烁
|mdtx.ui.radar_scanning = >> 雷达扫描中 <<
|mdtx.ui.basic = 基础对比
|mdtx.ui.set_target_wave = 设定查询波次
|mdtx.ui.path = 路径
|mdtx.ui.ui_icon_library = UI图标大全
|mdtx.ui.mods_enabled = | mod启用
|mdtx.ui.poked_you_check_the_message_dialog = [gold]戳了一下，请注意查看信息框哦~
|mdtx.ui.this_is_a_cheat_feature_njump_to_the = [red]这是一个作弊功能[]\n快速跳转到目标波次(不刷兵)
|mdtx.ui.current_frame_rate_locked_arg = 当前帧率锁定：@
|mdtx.ui.failed_to_read_playback = 读取回放失败!
|mdtx.ui.unit_rendering = 兵种显示
|mdtx.ui.carried_item = 携带物品:
|mdtx.ui.health_label = [red]血量：
|mdtx.ui.refresh_edited_logic = 更新编辑的逻辑
|mdtx.ui.shared_by = 分享者：
|mdtx.ui.unlock_and_allow_all_blocks = 显示并允许建造所有物品
|mdtx.ui.arg_s_arg_tiles = @s~@格
|mdtx.ui.load_map = 载入地图：
|mdtx.ui.placeholder_x = 倍
|mdtx.ui.spawned = [orange]生成！
|mdtx.ui.below_is_mdtx = 下面是[MDTX-
|mdtx.ui.team_selector = 队伍选择器
|mdtx.ui.mark_mode_tap_the_screen_to_place_a_mark = [cyan]标记模式,点击屏幕标记.
|mdtx.ui.view_recording_info = 查看录制信息
|mdtx.ui.remove_logic_lock = 移除逻辑锁定
|mdtx.ui.shortcut_scan_mode = 扫
|mdtx.ui.armor = [teal]装甲
|mdtx.ui.please_use_java_17_or_higher_to_run = )。请使用Java 17或更高版本运行MindustryX。\n[grey]该警告不存在设置，请更新Java版本。
|mdtx.ui.miner_ai = 矿机AI
|mdtx.ui.the_map_has_arg_world_processors_arg_instruction_lines_and_arg_characters = 地图共有@个世处，总共@行指令，@个字符
|mdtx.ui.logic_camera_lock_removed = 已移除逻辑视角锁定
|mdtx.ui.build_area = 建造区域
|mdtx.ui.zoom_x = 缩放: x
|mdtx.ui.wave_settings = 波次设定
|mdtx.ui.no_command_entered = 未输入指令
|mdtx.ui.block_rendering = 建筑显示
|mdtx.ui.builder_ai = 重建AI
|mdtx.ui.spawns_units_that_fly = [orange]生成的单位会飞起来
|mdtx.ui.arc_message_center = ARC-中央监控室
|mdtx.ui.game_resumed = 已继续游戏
|mdtx.ui.selection_range = 选择范围
|mdtx.ui.select_code = 选择代码
|mdtx.ui.tap_the_screen_to_capture_coordinates = [green]点击屏幕采集坐标
|mdtx.ui.this_is_a_message_from_mdtx = 这是一条来自 MDTX-
|mdtx.ui.add_team = 添加队伍
|mdtx.ui.before_adding_new_instructions_please_save_the_edited_instructions_first = [yellow]添加新指令前，请先保存编辑的指令
|mdtx.ui.you_were_poked_please_pay_attention_to_the_information_box = [orange]你被戳了一下，请注意查看信息框哦~
|mdtx.ui.global_range = 全局检查
|mdtx.ui.no_permission_to_edit_view_only = [yellow]当前无权编辑，仅供查阅
|mdtx.ui.cross = 十字
|mdtx.ui.shortcut_hitbox = 箱
|mdtx.ui.x_scan_speed = 倍搜索速度
|mdtx.ui.display_name = 显示名
|mdtx.ui.replay_not_loaded = 未加载回放!
|mdtx.ui.updated_edited_logic = [orange]已更新编辑的逻辑！
|mdtx.ui.power = 电力：
|mdtx.ui.unlock = 解禁
|mdtx.ui.cheat = 无限火力
|mdtx.ui.player_build_range = 玩家建造区
|mdtx.ui.damage = [red]伤害
|mdtx.ui.pick_up_payload = 捡起载荷
|mdtx.ui.fx = 效
|mdtx.ui.share_unit_count = 分享单位数量
|mdtx.ui.upload_failed_try_again = 上传失败，再重试一下？
|mdtx.ui.kotlin_language_standard_library = Kotlin语言标准库
|mdtx.ui.ring = 虚圆
|mdtx.ui.command_mode = 指挥模式
|mdtx.ui.force_boost = 强制助推
|mdtx.ui.permanent_status = <永久状态>
|mdtx.ui.frame_rate_simulation = 帧率模拟
|mdtx.ui.lock_the_last_marked_point = 锁定上个标记点
|mdtx.ui.effects_library = 特效大全
|mdtx.ui.share_inventory_status = 分享库存情况
|mdtx.ui.server_msg = 服务器信息
|mdtx.ui.size = 大小：
|mdtx.ui.toggle = 开关
|mdtx.ui.auto_refresh_variables = 变量自动更新
|mdtx.ui.vanilla = 原版
|mdtx.ui.no = 第
|mdtx.ui.fill_core_resources = 填满核心的所有资源
|mdtx.ui.force_skip_waves = 强制跳波
|mdtx.ui.event_wave = 事件~波次
|mdtx.ui.hide_logic_helper = 隐藏逻辑辅助器
|mdtx.ui.failed_to_create_replay = 创建回放出错!
|mdtx.ui.detached_camera = 视角脱离玩家
|mdtx.ui.squared = 平方对比
|mdtx.ui.add_panel = 添加面板
|mdtx.ui.add_destroyed_buildings_to_build_queue = 在建造列表加入被摧毁建筑
|mdtx.ui.surrender_vote = 法国军礼
|mdtx.ui.packet_count = 数据包总数：
|mdtx.ui.shortcut_block_render = 块
|mdtx.ui.lightning_arg_probability_arg_damage_arg_length_arg_x_speed = 闪电@概率~@伤害~@长度 @x速度
|mdtx.ui.could_not_check_for_updates_nplease_try_again_later = 检查更新失败，请稍后再试
|mdtx.ui.open_release_page = 打开发布页面
|mdtx.ui.rules = 规则：
|mdtx.ui.replay_creation_time = 回放创建时间:
|mdtx.ui.sec = 秒
|mdtx.ui.copied_this_chat_record = 已导出本条聊天记录
|mdtx.ui.wall_shadow_rendering = 墙体阴影显示
|mdtx.ui.server_info_build = 服务器信息版
|mdtx.ui.instant = 瞬间完成
|mdtx.ui.total_arg_arg_arg_arg_tile_radius = 总计@@@~@格半径
|mdtx.ui.frame_rate_lock_mode_turned_off_ncurrent_game_speed_arg_times = 已关闭帧率锁定模式\n当前游戏速度：@倍
|mdtx.ui.spawn_team = 生成队伍:
|mdtx.ui.share_power_status = 分享电力情况
|mdtx.ui.logic_art_website = 逻辑画网站
|mdtx.ui.contains_ground_x = 包含(地×
|mdtx.ui.waves_suffix = 波,
|mdtx.ui.god_mode = 创世神
|mdtx.ui.single_player_map_tools_only = 警告：该页功能主要供单机作图使用
|mdtx.ui.spawn_location = 生成位置:
|mdtx.ui.mindustryx_version = MindustryX | 版本号
|mdtx.ui.repair_ai = 修复AI
|mdtx.ui.n_took_units = \n[white]分走了单位:
|mdtx.ui.place_replace = 放置/替换
|mdtx.ui.effects_rendering = 特效显示
|mdtx.ui.rally = 集合
|mdtx.ui.download_and_install_update = 自动下载更新
|mdtx.ui.load_replay_file = 加载回放文件
|mdtx.ui.playback_version = 回放版本:
|mdtx.ui.copied_variable_attributes_n_arg = 复制变量属性\n@
|mdtx.ui.find_blocks = 查找方块
|mdtx.ui.paused = 已暂停
|mdtx.ui.hourglass = 沙漏：
|mdtx.ui.blueprint_code_link = 蓝图代码链接：
|mdtx.ui.template.atPlayer = <AT>戳了{0}[white]一下，并提醒他留意对话框
|mdtx.ui.template.copiedMemory = [cyan]复制内存[white]\n {0}
|mdtx.ui.template.currentVersion = 当前版本号: {0}
|mdtx.ui.template.currentWave = *** 当前波次: {0}
|mdtx.ui.template.introduction = 简介：{0}
|mdtx.ui.template.failedReadImage = 读取图片失败，请尝试更换图片\n{0}
|mdtx.ui.template.invalidBackgroundImage = 背景图片无效: {0}
|mdtx.ui.template.exportCount = 成功选取共{0}条记录，如下：\n
|mdtx.ui.template.exportHeader = 下面是[MDTX-{0}] 导出的游戏内聊天记录
|mdtx.ui.template.labelWithEmoji = {0} {1}
|mdtx.ui.template.loadMap = 载入地图：{0}
|mdtx.ui.template.exportMap = *** 当前地图名称: {0}(模式: {1})\n
|mdtx.ui.template.itemSelectionHeight = {0} 行
|mdtx.ui.template.itemSelectionWidth = {0} 列
|mdtx.ui.template.javaWarnDialog = Java版本 {0} 过低，不受支持。\n[grey]该警告不存在设置，请更新Java版本。
|mdtx.ui.template.javaWarnLog = Java版本 {0} 过低，不受支持。请使用Java 17或更高版本运行MindustryX。
|mdtx.ui.template.newVersion = [green]发现新版本[]: {0}
|mdtx.ui.template.savedBlueprint = 已保存蓝图：{0}
|mdtx.ui.template.windowTitle = MindustryX | 版本号 {0} | mod启用{1}/{2}
|mdtx.ui.template.shareHeader = 这是一条来自 MDTX-{0} 的分享记录\n
|mdtx.ui.template.shareCode = <ARCxMDTX><Schem>[black]一坨兼容[] {0}
|mdtx.ui.template.toggleState = {0}: {1}
|mdtx.ui.template.waveEvent = 波次：{0} | {1}
|mdtx.ui.template.waveContains = 包含(地×{0},空x{1}):
|mdtx.ui.template.waveEta = (还有{0}波, {1})
|mdtx.ui.template.waveTitle = 第{0}波
|mdtx.ui.template.atNoticeFrom = [gold]你被[white]{0}[gold]戳了一下，请注意查看信息框哦~
|
""".trimMargin()

    private val EN_PROPERTIES = """
|#UI
|mods.group.mod = Mod
|mods.group.internal = Internal Mod
|mods.disabled = Disabled Mod
|
|mods.recommend = [accent]MdtX[]Recommended Mods List
|mods.recommend.lastUpdated = Recommended List Last Updated: {0}
|mods.recommend.info = Selected Mods
|mods.recommend.mod.description = Selected Recommended Mod
|mods.recommend.mod.name = Mod: {0}
|mods.recommend.mod.author = Author: {0}
|mods.recommend.mod.minGameVersion = Minimum Supported Game Version: {0}
|mods.recommend.mod.lastUpdated = Last Updated: {0}
|mods.recommend.mod.stars = Github Stars: {0}
|
|alphaLoading = {jump}[gray]Loading...
|alphaLoadFailed = {sick}[gray]Load Failed...
|
|contentSelector = Select Content
|mdtx.report = Report Issue
|mdtx.qqLink = QQ Group
|
|mdtx.share.item = {0}: Stock {1}, Production {2}/s
|mdtx.share.unit = {0}: Count {1}, Limit {2}
|
|commit.recentUpdates = Recent Updates
|commit.title = Commits
|
|overlayUI.tips = [gold]Tips:[]\n1. Default PC shortcut is Z, you can change it in settings.\n2. After locking the panel, it can be displayed in-game.\n3. Not all panels need to be locked, the left switch can be used as a collapse button.\n4. After locking, the content area remains unchanged, and will snap to the edge.\n5. On mobile, you can adjust zoom in window settings, information display can be abbreviated, buttons can be enlarged.
|forceJoin.tips = [gold]MDTX[]: The target version may be compatible, you can choose to disguise the version to force join.\nIf [red]network error[] or other problems occur, it means incompatible.\n\nTIPS: Backward compatibility (v146-current version) is an MDTX exclusive feature.
|#end UI
|
|status.slow.name = Slow
|status.shielded.name = Shielded
|status.corroded.name = Corroded
|status.disarmed.name = Disarmed
|status.invincible.name = Invincible
|status.fast.name = Fast
|
|#StatExt
|category.combat = Combat
|category.moreContent.name = More Content Adaptation
|category.movement = Movement
|category.support = Support
|
|stat.can_overdrive = Can Overdrive
|stat.cost = Build Time Cost
|stat.health_scaling = Building Health Scaling
|stat.hardness = Hardness
|stat.buildable = Buildable
|stat.boil_point = Boiling Point
|stat.drag_multiplier = Drag Multiplier
|
|stat.buffer_capacity = Buffer Capacity
|stat.regen_speed = Regeneration Speed
|stat.mend = Mend Amount
|stat.mend_reload = Mend Interval
|stat.mend_speed = Mend Speed
|stat.warmup_partial = Warmup Time
|stat.warmup_time = Full Warmup Time
|stat.warmup_power = Total Warmup Power
|
|stat.rotate_speed = Rotation Speed
|stat.boost_multiplier = Boost Speed Multiplier
|stat.drown_time_multiplier = Drown Time Multiplier
|stat.mine_level = Mining Level
|
|stat.estimate_dps = Estimated DPS
|stat.ai_controller = Default AI
|stat.targets = Targets
|stat.ammo_type = Ammo Type
|stat.ammo_capacity = Ammo Capacity
|
|#end StatExt
|
|#SettingsV2
|settings.category.settingV2 = [gold]MindustryX
|settingV2.reset = [red]Reset to Default
|settingV2.onlyModified = Only show modified settings
|
|settingV2.autoFill.category = Quick Fill
|settingV2.autoFill.cooldown.name = Operation Cooldown (ms)
|settingV2.autoFill.cooldown.description = Too small value may cause server kick
|settingV2.autoFill.minFill.name = Minimum Fill Amount
|settingV2.autoFill.fillStorageBlock.name = Allow Fill into Container/Vault
|settingV2.autoFill.fillDistribution.name = Allow Fill into Plastanium Conveyor/Bridge
|
|settingV2.coreItems.category = Team Resource Display
|settingV2.coreItems.showItem.name = Show Core Items
|settingV2.coreItems.showUnit.name = Show Unit Count
|settingV2.coreItems.showPlan.name = Show Building Count
|settingV2.coreItems.showPower.name = Show Power Grid Info
|setting.coreitems.name = Display Core Items (Deprecated, please use V2 settings)
|
|settingV2.AutoUpdate.category = Update Checker
|settingV2.AutoUpdate.showUpdateDialog.name = Notify on New Versions
|settingV2.AutoUpdate.ignoreOnce.name = Skip This Version
|settingV2.AutoUpdate.ignoreUntil.name = Snooze for 7 Days
|
|settingV2.quickButtons.category = Quick Buttons
|settingV2.quickButtons.columns.name = Button Columns (Per Row)
|settingV2.quickButtons.customButtons.name = Custom Commands
|
|settingV2.damagePopup.category = Health Popups (Damage Popups)
|settingV2.damagePopup.enable.name = Enable Health Popups
|settingV2.damagePopup.playerOnly.name = Player Only (Includes Controlled)
|settingV2.damagePopup.showHeal.name = Show Heal Popups [grey](Otherwise Only Shows Damage)
|settingV2.damagePopup.minHealth.name = Minimum Health Threshold
|
|settingV2.entityRender.category = Entity Rendering
|settingV2.entityRender.unitHide.name = Hide Units
|settingV2.entityRender.unitHideExcludePlayers.name = Always Show Player Units
|settingV2.entityRender.unitHideMinHealth.name = Hide Units Below Health Threshold
|settingV2.entityRender.noBulletShow.name = Hide Bullets [grey]Significantly reduces render (DW) cost
|settingV2.entityRender.unitHitbox.name = Show Unit Hitboxes
|settingV2.entityRender.payloadPreview.name = Payload Pickup Preview
|
|settingV2.gameUI.category = Game UI
|settingV2.gameUI.spawnerWaveDisplay.name = Spawn Point Wave Info Display
|settingV2.gameUI.transportScan.name = Transport Scan Mode
|settingV2.gameUI.menuFloatText.name = Home Floating Text
|settingV2.gameUI.announceRtsTake.name = Notify When Controlled Unit Taken by Others
|settingV2.gameUI.deadOverlay.name = Show UI While Dead/Spectating [orange]May Crash
|settingV2.gameUI.deadOverlay.description = Keeps UI visible for viewing info and copying blueprints during spectate
|settingV2.gameUI.invertMapClick.name = Invert Mini-map Clicks
|settingV2.gameUI.invertMapClick.description = After invert: left-drag, right-open
|settingV2.gameUI.arcSpecificTable.name = Top Left ARC Info Display (Deprecated)[orange][Takes Effect on Restart]
|settingV2.gameUI.itemSelectionHeight.name = Build Menu Rows (Bottom Right)
|settingV2.gameUI.itemSelectionWidth.name = Build Menu Columns (Bottom Right)
|settingV2.gameUI.researchViewer.name = Tech Tree Viewer
|settingV2.gameUI.extendedCommandTable.name = RTS Extension Buttons
|settingV2.gameUI.overlayButton.name = OverlayUI Button [grey]PC recommended shortcut: Z
|
|settingV2.additionInventoryColumns.name = Additional building inventory and item configuration columns
|settingV2.additionInventoryColumns.description = Involves core item bar, building item bar and item configuration bar, editor block bar, etc.
|settingV2.minimapSize.name = Minimap Size
|settingV2.staticShieldsBorder.name = Static Shield Border
|settingV2.allUnlocked.name = Show All Content (Including Hidden)
|settingV2.noPlayerHitBox.name = Disable Player Hitbox [gray]Mild Cheat
|settingV2.arcTurretPlaceCheck.name = Show No-Build Zones When Placing Turrets
|settingV2.arcTurretPlacementItem.name = Show Different Ammo Ranges for Turrets
|settingV2.githubMirror.name = GitHub Mirror Acceleration (WZ Mirror)
|settingV2.githubMirror.description = Optimizes global server list and mod browser functions
|settingV2.replayRecord.name = Multiplayer Recording
|settingV2.replayRecord.description = Automatically records gameplay, output in saves folder\nRecording files may be large, remember to clean up
|settingV2.maxSchematicSize.name = Max Selection (Schematic) Size
|settingV2.autoSelectSchematic.name = Auto Schematic Select      [gray]Auto-filters when opening schematics
|settingV2.collectMetrics.name = Anonymous Metrics Collection
|settingV2.collectMetrics.description = Anonymously collect crash logs, runtime environment and other information\nTo help developers improve the game
|settingV2.worldCreator.name = God Mode Builder
|settingV2.worldCreator.description = Lift placement restrictions; place or remove any block.
|settingV2.terrainSchematic.name = Terrain Schematic
|settingV2.terrainSchematic.description = Copy terrain/walls into schematics; paste them with God Mode Builder.
|
|settingV2.arcExtra.category = ARC - Extended Features
|settingV2.arcExtra.colorizedContent.name = Use colored item names [grey] — may reduce readability
|settingV2.arcExtra.backgroundPath.name = Home - Custom Background Path
|settingV2.arcExtra.backgroundPath.description = Full path required
|settingV2.arcExtra.radarMode.name = Radar Scan Speed
|settingV2.arcExtra.radarSize.name = Radar Size
|settingV2.arcExtra.schematicShare.name = Receive Schematic Share
|
|settingV2.block.category = Block Settings
|settingV2.block.rotateCanvas.name = Rotate Canvas When Rotating Schematic [orange]May Cause Crash, Use Cautiously
|settingV2.block.arcChoiceUiIcon.name = Show Unloader/Sorter Item Icons
|settingV2.block.hiddenItemTransparency.name = Bridge/Junction Item Opacity
|settingV2.block.overdriveZoneTransparency.name = Overdrive Zone Opacity
|settingV2.block.mendZoneTransparency.name = Repair Zone Opacity
|settingV2.block.healthBarMinHealth.name = Minimum Building Health for HP Bar
|settingV2.block.renderLevel.name = Block Render Level
|settingV2.block.showOtherTeamState.name = View Other Team’s Building State (Read-Only)
|settingV2.block.editOtherBlock.name = Edit Other Team Buildings     [yellow][Single Player Only, Cheat Feature]
|settingV2.block.logicDisplayNoBorder.name = Remove Display Screen Border
|settingV2.block.arcPlacementEffect.name = Building Placement Effects
|
|settingV2.logicSupport.category = Logic Support
|settingV2.logicSupport.visible.name = Show Logic Helpers in Editor
|settingV2.logicSupport.changeSplash.name = Flash on Variable Change
|settingV2.logicSupport.memoryColumns.name = Memory Cell Display Columns
|settingV2.logicSupport.memoryDecimal.name = Memory Cell Decimal Precision
|
|settingV2.overlayUI.category = Overlay UI
|settingV2.overlayUI.debug.name = Debug Panel
|settingV2.overlayUI.auxiliaryTools.name = Auxiliary Buttons
|settingV2.overlayUI.quickTool.name = Quick Settings
|settingV2.overlayUI.mappingTool.name = Mapping Toolbox
|settingV2.overlayUI.advanceBuildTool.name = Batch Build Tool
|settingV2.overlayUI.teamsStats.name = Multi-team Resource Display
|settingV2.overlayUI.coreItems.name = Team Resource Display
|settingV2.overlayUI.waveInfo.name = New Wave Info Display
|settingV2.overlayUI.controlGroup.name = RTS Control Group
|settingV2.overlayUI.markAndShare.name = Mark and Share
|
|settingV2.debug.category = Special Settings (Unstable)
|settingV2.debug.renderSort.name = Render Sorting
|settingV2.debug.renderSort.description = Sorts rendering by texture\nCan improve render performance by 50% in multi-atlas (mod-heavy) environments, but may cause artifacts
|settingV2.debug.reliableSync.name = Use TCP for All Data Packets
|settingV2.debug.limitUpdate.name = Limit Updates
|settingV2.debug.limitUpdate.description = Greatly reduces LG overhead, but halts offscreen simulation\nStrongly discouraged in single player and may desync on server
|#end SettingsV2
|
|# Binding
|keybind.arcDetail.name = Radar Scan
|keybind.arcScanMode.name = Scan Details
|keybind.oreAdsorption.name = Ore Auto Adsorption
|keybind.showRTSAi.name = Show Unit Control
|keybind.superUnitEffect.name = Show Player Range
|keybind.overlayUI.name = Toggle OverlayUI
|# end Binding
|
|# editor增强
|toolmode.square2 = Square (Diameter)
|toolmode.square2.description = Same as square, but size uses diameter (ARC feature)
|#end editor增强
|
|bar.reloadDetail = Reload: {0}%
|bar.warmupDetail = Warmup: {0}%
|bar.ammoDetail = Ammo: {0}/{1}
|
|
|marker.Mark.name = Mark
|marker.Gather.name = Gather
|marker.Attack.name = Attack
|marker.Defend.name = Defend
|marker.What.name = What
|
|keybind.point.name = Mark
|keybind.lockonLastMark.name = Lock on Last Mark
|keybind.toggle_block_render.name = Toggle Building Display
|keybind.toggle_unit.name = Toggle Unit Display
|keybind.focusLogicController.name = Lock to Controlled Processor
|keybind.placeRouterReplacement.name = Quick Replace Conveyor (Router/Bridge)
|
|
|# ARC设置
|category.arcAddTurretInfo.name = More Turret Attributes
|category.arcAddUnitInfo.name = More Unit Attributes
|category.arcCDisplayBlock.name = Building Display
|category.arcCGraphicsOther.name = Others
|category.arcCOverview.name = Global Settings
|category.arcCgameview.name = Game View
|category.arcCgamewindow.name = Game Interface
|category.arcMassDriverInfo.name = Mass Driver Guide Line
|category.arcPlayerEffect.name = Player Cool Effects
|category.arcWeakCheat.name = Weak Cheat Features
|
|setting.alwaysShowUnitRTSAi.name = Units: Executed RTS Commands
|setting.arcAlwaysTeamColor.name = Player List: Always Draw Team Colors
|setting.arcBuildInfo.name = [cyan]Build Range
|setting.arcdrillmode.name = Drill: Always Bright Minerals
|setting.blockBars.name = Building Attributes
|setting.blockBars_mend.name = Repair: Progress Bar
|setting.blockWeaponTargetLine.name = Turret: Targeting Line
|setting.blockWeaponTargetLineWhenIdle.name = Turret: Targeting Line (Idle)
|setting.blockdisabled.name = Always Show Building Disabled State
|setting.hoveredTileInfo.name = Show Hovered Tile/Building Name
|setting.mass_driver_line.name = Show Mass Driver Guide Line
|setting.mass_driver_line_color.name = [pink]Mass Driver Guide Line: Color
|setting.mass_driver_line_interval.name = Mass Driver Guide Line: Arrow Interval
|setting.overrideSkipWave.name = Feature: Ignore Skip Wave Limit
|setting.playerEffectColor.name = Player Range: Color
|setting.playerEffectCurStroke.name = Player Range: Thickness
|setting.playerNeedShooting.name = [red]Time Management Master
|setting.rtsWoundUnit.name = Unit Filter: Low Health Threshold
|setting.save_more_map.name = Save Campaign and Editor Maps
|setting.showTurretAmmo.name = Turret: Ammo Type
|setting.showTurretAmmoAmount.name = Turret: Ammo Amount
|setting.superUnitEffect.name = [pink]Player Special Effect Range
|setting.turretAlertRange.name = Turret: Alert Range
|setting.turretForceShowRange.name = Turret: Force Show Range [gray]Can be used to show range in editor
|setting.turretShowRange.name = Turret: Range
|setting.unitHealthBar.name = Unit Attributes
|setting.unitItemCarried.name = Unit Carried Items
|setting.unitLogicMoveLine.name = Logic Control: Movement Path
|setting.unitLogicTimerBars.name = Logic Control: Timer Bars
|setting.unitTargetType.name = [pink]Player's Target Style
|setting.unitWeaponRange.name = Unit Weapon Range: Range Warning
|setting.unitWeaponRangeAlpha.name = Unit Weapon Range: Opacity
|setting.unitWeaponTargetLine.name = Unit Weapon Target
|setting.unitbuildplan.name = Units: Build Sequence Display
|settings.arc = ARC Features
|
|# ARC增加
|bar.drillcantmine = Current drill cannot mine this mineral
|revealedblocks = Revealed Blocks
|rules.aiCoreSpawn = AI Core Spawn
|rules.canGameOver = Allow Game Over [gray](If there are no other ways to end the game, not recommended to enable)
|rules.cheat = Cheat
|rules.coreDestroyClear = Clear nearby buildings when a core is destroyed
|rules.disableOutsideArea = Disable Outside Area
|rules.dynamicColor = Explored Fog Color [gold]X[]
|rules.infiniteAmmo = Infinite Unit Ammo [gray](Not recommended to disable)
|rules.staticColor = Unexplored Fog Color [gold]X[]
|rules.title.arcExperimental = Hidden Settings [red](Experimental features, may affect stability)
|rules.unitPayloadUpdate = Blocks carried by units will operate
|rules.winWave = Win Wave [gold]X[] [gray](Automatically stops after reaching the specified wave)
|schematic.preview = Preview
|settings.maxMsgRecorded.name = Maximum Recorded Messages
|shield.phaseboost = [stat]+{0}[lightgray] cells [stat]+{1}[] shield capacity
|shield.regenspeed = [stat]{0}[lightgray]x regeneration speed
|
|# 原版额外内容
|content.planet.name = Planet
|content.weather.name = Weather
|unit.anthicus-missile.name = Anthicus Missile
|unit.disrupt-missile.name = Disrupt Missile
|unit.quell-missile.name = Quell Missile
|unit.scathe-missile.name = Scathe Missile
|team.neoplastic.name = Neoplastic
|
|ability.energyfield.maxtargets = [lightgray]Max targets: [white]{0}
|ability.energyfield.sametypehealmultiplier = [lightgray]Same-type heal: [white]{0}%
|bar.drilltierreq = Requires {0} drill tier (current: {1})
|block.armored-duct.name = Armored Duct
|block.large-shield-projector.name = Large Shield Projector
|rules.waitForWaveToEnd = Wait for wave to end [gray]Next wave starts after all enemies are defeated
|schematic.tagged = {0} tagged schematics
|unit.incite.name = Incite (T4)
|unit.obviate.name = Obviate (T5)
|unit.quell.name = Quell (T4)
|unit.disrupt.name = Disrupt (T5)
|ability.liquidregen = Liquid Regen
|database.patched = Modified by content pack
|rules.logicunitbuild = Allow logic-controlled unit building
|mdtx.rules.possessionAllowed = Allow unit possession
|mdtx.rules.disableRebuild = Disable rebuilding
|mdtx.rules.enableInfiniteAmmoAll = Enable infinite ammo for all teams
|mdtx.rules.disableInfiniteAmmoAll = Disable infinite ammo for all teams
|mdtx.rules.moreTeamOptions = More team options
|mdtx.rules.moreTeamSelect = More team selection
|mdtx.rules.customBackground = Custom background [lightgray](requires empty floor)
|mdtx.rules.bgZoom = Zoom
|mdtx.rules.bgPosX = Position x
|mdtx.rules.bgPosY = Position y
|mdtx.rules.bgPosZ = Position z
|mdtx.waves.toggleDisplayMode = Toggle display mode
|mdtx.editor.centerHint = Right-click the brush icon or other icons to open advanced drawing options.\nThis feature is exclusive to MindustryX.
|mdtx.editor.otherTeams = [violet]Other Teams
|mdtx.editor.grid = Grid:
|mdtx.editor.brush = Brush:
|mdtx.waves.legend = \uE86D count · \uE813 hp+shield · \uE810 buffed hp+shield · \uE86E est DPS
|mdtx.waves.waveIndex = Wave [accent]{0}[]
|mdtx.waves.noEnemies = No enemies this wave
|mdtx.waves.loadMore = Load More Waves
|mdtx.waves.carryItem = Carried item[gold]X[]:
|mdtx.waves.carryItemDenied = [red]This unit cannot carry items
|mdtx.waves.carryPayload = Carried payload[gold]X[]:
|mdtx.waves.carryPayloadDenied = [red]This unit cannot carry payloads
|mdtx.logic.convertFailed = [orange]Warning: convert failed, check the format.
|mdtx.logic.discardChanges = [orange]Discard Changes
|mdtx.logic.confirmDiscard = Discard changes?
|mdtx.logic.jumpLine = [gold]Jump line:[] {0}
|mdtx.unit.payload = Payload: {0}/{1} {2}
|mdtx.unit.stat.hp = HP
|mdtx.unit.stat.dmg = DMG
|mdtx.unit.stat.rld = RLD
|mdtx.unit.stat.spd = SPD
|mdtx.unit.stat.bld = BLD
|mdtx.unit.stat.drag = DRG
|mdtx.unit.stat.arm = ARM
|mdtx.unit.mineLevelFormat = @ tier
|mdtx.weapon.range = [lightgray]Range: [stat]{0}[] blocks
|mdtx.weapon.rotateSpeed = [lightgray]Rotate speed: [stat]{0}[]°/s
|mdtx.weapon.rotateLimit = [lightgray]Rotate limit: [stat]{0}[] {1}
|mdtx.content.shareBrief = ♐S
|mdtx.content.shareDetail = ♐D
|mdtx.database.unlock = Unlock
|mdtx.forceJoin.join = Force Join
|mdtx.keybind.unbind = Unbind
|mdtx.planet.sectorName = Sector Name
|mdtx.research.prereqMissing = [red]Prerequisite missing
|mdtx.research.prereqLine = {0}\n[red]Prerequisite missing
|mdtx.schematics.archive = Schematic Archive
|mdtx.schematics.converter = Image Converter
|mdtx.schematics.converterWithIcons = Image Converter {0}{1}{2}
|mdtx.schematics.techTree = Tech:
|mdtx.schematics.assistFilter = Filter:
|mdtx.schematics.canBuildTip = Buildable (core has resources and map allows it)
|mdtx.schematics.contains = Must contain:
|mdtx.schematics.mustContainTip = Schematic must include this block
|mdtx.schematics.filterMode = [orange]Filter mode[white]: schematic must contain {0}
|mdtx.schematics.shareChat = Share to Chat
|mdtx.schematics.copyAdvanced = Copy with Intro
|mdtx.schematics.fromServer = Schematic from server
|mdtx.schematics.fromPlayer = Schematic from {0}
|mdtx.schematics.autoTag = Auto Tags
|mdtx.schematics.logicCopied = Logic code copied
|mdtx.hud.enterMarkMode = Enter mark mode
|mdtx.hud.teamPrefix = Add /t prefix
|mdtx.hud.lockLastMark = Lock last mark
|mdtx.hud.more = More
|mdtx.hud.scale = Scale: {0}
|mdtx.hud.enemyCores = Enemy cores: [orange]{0}
|mdtx.hud.wave = Wave: [orange]{0}
|mdtx.rts.highHealth = High-HP units
|mdtx.rts.lowHealth = Low-HP units
|mdtx.rts.attackUnit = Attack units
|mdtx.rts.supportUnit = Support units
|mdtx.rts.airUnit = Air units
|mdtx.rts.landUnit = Land units
|mdtx.rts.navalUnit = Naval units
|mdtx.rts.select = RTS: selected {0}!
|mdtx.rts.remove = RTS: removed {0}!
|mdtx.player.copiedName = Copied name: {0}
|mdtx.bar.charge = Charge: {0} / {1}
|mdtx.bar.boost = Boost: {0}
|mdtx.bar.drillSpeed = Drill speed: {0}{1}/s
|mdtx.apk.installFailed = APK install failed
|mdtx.stat.buildingDamage = {0}[lightgray]x building damage
|mdtx.stat.range = [lightgray]Range {0} [lightgray]tiles
|mdtx.stat.reloadRate = {0}[lightgray]x fire rate
|mdtx.stat.pierceFalloff = {0}% falloff
|mdtx.stat.pierceUnlimited = unlimited
|mdtx.stat.pierceTimes = {0}x
|mdtx.stat.pierceLabel = pierce[lightgray]
|mdtx.stat.pierceBoth = buildings & units
|mdtx.stat.pierceBuilding = buildings
|mdtx.stat.pierceUnit = units
|mdtx.stat.pierceElectric = [stat](electric)
|mdtx.stat.pierce = {0} pierce[lightgray]{1}{2}
|mdtx.stat.homing = [stat]Homing[lightgray]~[]{0}°/s[lightgray]~[]{1}[lightgray] tiles
|mdtx.stat.emp.summary = [stat]EMP~{0}[lightgray] tiles[]~[white]\uE810[]{1}%/[white]\uE86D[]{2}%~[white]\uF899[][green]{3}%[]/[negstat]{4}%[]
|mdtx.stat.emp.powerDamage = [stat]Deals {0}% bullet damage to enemy power-grid buildings
|mdtx.stat.emp.unitDamage = [stat]Deals {0}% bullet damage to enemy units
|mdtx.stat.emp.allyBoost = [stat]Boosts allied powered buildings to {0}%
|mdtx.stat.emp.enemySlow = [stat]Slows enemy power-grid buildings to {0}%
|mdtx.stat.lightningDamage = Lightning~[stat]{0}[] dmg~
|mdtx.stat.lightningLengthRange = [stat]{0}~{1}[] length
|mdtx.stat.lightningLength = [stat]{0}[] length
|
|# Stylized translations (no need to localize in other languages)
|
|# hardcoded ui texts extracted from source
|mdtx.ui.empty_selection_area_hint = The currently selected area is empty. Please use F to plan the area.
|mdtx.ui.sync_a_wave = Sync a wave
|mdtx.ui.miner_ai_ore_filter = Miner AI - Ore Filter
|mdtx.ui.blueprint_code_n = Blueprint code: \n
|mdtx.ui.copied_print_buffer_n_arg = Copied print buffer\n@
|mdtx.ui.message_center = Message Center
|mdtx.ui.lock = Lock
|mdtx.ui.event_map_load = Event~Map Load
|mdtx.ui.logic_helper_x = Logic Helper[gold]X[]
|mdtx.ui.surrender_vote_confirm = Are you sure you want to surrender?
|mdtx.ui.shortcut_observer_mode = O
|mdtx.ui.original_size = Original size
|mdtx.ui.current_unit_cannot_build = [red]Current unit cannot build
|mdtx.ui.unit = Unit:
|mdtx.ui.zoom = Zoom
|mdtx.ui.add_prefix_t = Add prefix /t
|mdtx.ui.observer_mode = Observer Mode
|mdtx.ui.shortcut_unit_render = U
|mdtx.ui.export = Export
|mdtx.ui.air_only = Air only
|mdtx.ui.logic_notice = Logic~Notice
|mdtx.ui.share_wave_information = Share wave information
|mdtx.ui.name = Name
|mdtx.ui.wave_in_prefix = in
|mdtx.ui.warning_image_may_be_too_large_please_try_compressing_image = [orange]Warning: Image may be too large, please try compressing image
|mdtx.ui.all_players = All players
|mdtx.ui.icon = Icon
|mdtx.ui.bullet_rendering = Bullet Rendering
|mdtx.ui.failed_to_read_image_please_try_another_image_n = Failed to read image, please try another image\n
|mdtx.ui.mark_player = Mark~Player
|mdtx.ui.chat_history_exceeding_the_limit_will_be_cleared_when_loading_the_map = Chat history exceeding the limit will be cleared when loading the map
|mdtx.ui.wave = Wave
|mdtx.ui.player_name = Player name:
|mdtx.ui.randomly_generated_within_this_range_near_the_target_point = Randomly generated within this range near the target point
|mdtx.ui.on = On
|mdtx.ui.slow_the_flow_of_time_to_half = Slow the flow of time to half
|mdtx.ui.ore_info = Ore Info
|mdtx.ui.shortcut_fog = F
|mdtx.ui.check_for_updates = Check for Updates
|mdtx.ui.always_on = Always On
|mdtx.ui.exported_in_game_chat_history = ] Exported in-game chat history
|mdtx.ui.allowed_range_2_9999 = Allowed range: 2~9999
|mdtx.ui.clear_all_core_resources = Clear all core resources
|mdtx.ui.arc_image_converter = ARC Image Converter
|mdtx.ui.artboard = Artboard++
|mdtx.ui.radar_toggle = Radar Toggle
|mdtx.ui.current_map_name = *** Current map name:
|mdtx.ui.ui_toolkit = UI Toolkit
|mdtx.ui.ring_cross = Ring Cross
|mdtx.ui.please_don_t_tag_too_often = Please don't tag too often!
|mdtx.ui.message_arg_js_starts_with_script = Message (@js starts with script)
|mdtx.ui.mark_map_location = Mark map location
|mdtx.ui.temporary_status = <Temporary State>
|mdtx.ui.blueprint_name = Blueprint name:
|mdtx.ui.unit_factory_x = Unit Factory-X
|mdtx.ui.the_blueprint_code_is_too_long_please_click_the_link_to_view_it = The blueprint code is too long, please click the link to view it
|mdtx.ui.ground_only = Ground only
|mdtx.ui.flash_on_change = Flash on Change
|mdtx.ui.show_all = Show all
|mdtx.ui.reset = Reset
|mdtx.ui.shortcut_server_info = V
|mdtx.ui.shield = [yellow]Shield:
|mdtx.ui.spawn_range = Spawn range:
|mdtx.ui.click_the_screen_to_return = [green]Click the screen to return
|mdtx.ui.team_id = Team ID:
|mdtx.ui.refresh_interval = Refresh interval
|mdtx.ui.export_chat_history = Export chat history
|mdtx.ui.scan_mode = Scan Mode
|mdtx.ui.arc_ai_configurator = ARC-AI Configurator
|mdtx.ui.resistance = [purple]Resistance
|mdtx.ui.load_unit = Load Unit
|mdtx.ui.unit_factory = Unit Factory
|mdtx.ui.tiles = tiles
|mdtx.ui.zoom_zoom = Zoom: 
|mdtx.ui.automatically_refresh_variables = Automatically refresh variables
|mdtx.ui.fog_of_war = Fog of War
|mdtx.ui.maximum_storage_of_chat_history_too_high_may_cause_lag = Maximum storage of chat history (too high may cause lag):
|mdtx.ui.show_all_message_blocks = Show all message blocks
|mdtx.ui.attack_no_border = Attack (no border)
|mdtx.ui.arg_shield_capacity_arg_grid_arg_recovery_arg_s_cooldown = @ shield capacity ~ @ grid ~ @ recovery ~ @s cooldown
|mdtx.ui.staging_area = Staging area
|mdtx.ui.there_are_no_enemies_in_this_wave = There are no enemies in this wave
|mdtx.ui.shortcut_surrender_vote = [white]S
|mdtx.ui.construction_suspended = Construction suspended
|mdtx.ui.waves = Waves:
|mdtx.ui.hide_all_buildings = Hide all buildings
|mdtx.ui.cancel = Cancel
|mdtx.ui.preview_releases_n_faster_updates_new_features_bug_fixes = Preview Releases\n(faster updates, new features, bug fixes)
|mdtx.ui.open_playback_file = Open playback file
|mdtx.ui.copied_successfully = Copied successfully:
|mdtx.ui.minimap = Minimap
|mdtx.ui.sandbox = Sandbox
|mdtx.ui.build_speed = [accent]Build Speed
|mdtx.ui.recording_ended = Recording ended
|mdtx.ui.chat = Chat
|mdtx.ui.team_range = Team range
|mdtx.ui.wave_info = Wave Info
|mdtx.ui.defender_ai = Defender AI
|mdtx.ui.recording_error = Recording error!
|mdtx.ui.show_building_status_only = Show building status only
|mdtx.ui.current_game_speed_arg_times = Current game speed: @ times
|mdtx.ui.pause_logic_game_execution = Pause logic (game) execution
|mdtx.ui.return_to_original_speed = Return to original speed
|mdtx.ui.air_x = , air x
|mdtx.ui.flight_mode = Flight mode
|mdtx.ui.automatically_save_as_blueprint = Automatically save as blueprint
|mdtx.ui.built_in_prefix = [Built-in]
|mdtx.ui.item = Item
|mdtx.ui.speed_up_time_to_2x = Speed up time to 2x
|mdtx.ui.enter_the_conveyor_belt = Enter the conveyor belt
|mdtx.ui.blueprint_cost = Blueprint cost:
|mdtx.ui.scaled_size = Scaled size
|mdtx.ui.mark_coordinates = Mark~Coordinates
|mdtx.ui.tip_all_schematics_containing_processors = TIP: All schematics containing processors
|mdtx.ui.shortcut_wall_shadow = W
|mdtx.ui.panels_currently_unavailable = Panels currently unavailable:
|mdtx.ui.select_and_import_pictures_which_can_be_converted = Select and import pictures, which can be converted into artboards, pixel paintings or logic paintings.
|mdtx.ui.stable_releases = Stable Releases
|mdtx.ui.more_teams = More Teams
|mdtx.ui.set_target = Set target
|mdtx.ui.movement_speed = [cyan]Movement speed
|mdtx.ui.frame_rate_lock_mode_enabled_ncurrent_frame_rate_lock_arg = Frame rate lock mode enabled \nCurrent frame rate lock: @
|mdtx.ui.server_ip = Server IP:
|mdtx.ui.current_selection_is_empty_select_a_block_in_the_inventory = [yellow]Current selection is empty; select a block in the inventory.
|mdtx.ui.off = Off
|mdtx.ui.shortcut_message_center = M
|mdtx.ui.index = Index
|mdtx.ui.current_map_arg = Current map: @
|mdtx.ui.release_notes = Release Notes
|mdtx.ui.clone = Clone
|mdtx.ui.saved_to_clipboard = Saved to clipboard
|mdtx.ui.recording_arg = Recording: @
|mdtx.ui.there_are_too_many_buildings_to_avoid_lag_and_only_keep_the_first_1000_plans = [yellow]There are too many buildings to avoid lag and only keep the first 1000 plans.
|mdtx.ui.load_building = Load Building
|mdtx.ui.generated_label = Generated
|mdtx.ui.canvas = Canvas
|mdtx.ui.unlimited = Unlimited
|mdtx.ui.buildings = Buildings:
|mdtx.ui.auto_attack = Auto Attack
|mdtx.ui.playback_length = Playback length:
|mdtx.ui.liquids = Liquids
|mdtx.ui.all = All
|mdtx.ui.replay_stats = Replay Stats
|mdtx.ui.hp = [acid]HP
|mdtx.ui.pause_time = Pause time
|mdtx.ui.restore_current_wave = Restore current wave
|mdtx.ui.arg_arg_ndistance_arg = @,@\nDistance: @
|mdtx.ui.successfully_selected_a_total_of = Successfully selected a total of
|mdtx.ui.pixel_art = Pixel Art
|mdtx.ui.terrain_blueprint = Terrain Blueprint
|mdtx.ui.each_cell_absorbs_arg_s_arg_arg_arg_s_and_returns_blood_maximum_arg_s = Each cell absorbs @/s@@~heals @/s~up to @/s
|mdtx.ui.attack_speed = [violet]Attack speed
|mdtx.ui.toggle_your_team_s_cheat = Toggle your team's Cheat
|mdtx.ui.generate_quantity = Generate quantity:
|mdtx.ui.unique = Unique
|mdtx.ui.drop_payload = Drop Payload
|mdtx.ui.clear = Clear
|mdtx.ui.reset_all_links = Reset all links
|mdtx.ui.editor = Editor
|mdtx.ui.attack = Attack
|mdtx.ui.select_image_png = Select image[white](png)
|mdtx.ui.hitbox_overlay = Hitbox Overlay
|mdtx.ui.logic_announcement = Logic~Announcement
|mdtx.ui.team = Team:
|mdtx.ui.self_destruct = Self-Destruct
|mdtx.ui.copied_variable_name_n_arg = Copied variable name\n@
|mdtx.ui.ore_count_surface_wall = Ore Count (surface/wall)
|mdtx.ui.you_are_already_on_the_latest_version = You are already on the latest version.
|mdtx.ui.hue_mode = Hue mode:
|mdtx.ui.load_self = Load self
|mdtx.ui.auto_fill = Auto Fill
|mdtx.ui.arc_ore_statistics = ARC Ore Statistics
|mdtx.ui.extract_code_from_schematic = Extract code from schematic
|mdtx.ui.shortcut_bullet_render = P
|mdtx.ui.fixed_size = Fixed size
|mdtx.ui.command = Command
|mdtx.ui.color = Color
|mdtx.ui.flash_on_variable_change = Flash on variable change
|mdtx.ui.radar_scanning = >> Radar Scanning <<
|mdtx.ui.basic = Basic
|mdtx.ui.set_target_wave = Set target wave
|mdtx.ui.path = Path
|mdtx.ui.ui_icon_library = UI Icon Library
|mdtx.ui.mods_enabled = | mods enabled
|mdtx.ui.poked_you_check_the_message_dialog = [gold]You were poked; check the message dialog.
|mdtx.ui.this_is_a_cheat_feature_njump_to_the = [red]This is a cheat feature[]\nJump to the target wave instantly (without spawning enemies)
|mdtx.ui.current_frame_rate_locked_arg = Current frame rate locked: @
|mdtx.ui.failed_to_read_playback = Failed to read playback!
|mdtx.ui.unit_rendering = Unit Rendering
|mdtx.ui.carried_item = Carried item:
|mdtx.ui.health_label = [red]HP:
|mdtx.ui.refresh_edited_logic = Refresh edited logic
|mdtx.ui.shared_by = Shared by:
|mdtx.ui.unlock_and_allow_all_blocks = Unlock and allow all blocks
|mdtx.ui.arg_s_arg_tiles = @s~@ tiles
|mdtx.ui.load_map = Load map:
|mdtx.ui.placeholder_x = x
|mdtx.ui.spawned = [orange]spawned!
|mdtx.ui.below_is_mdtx = Below is [MDTX-
|mdtx.ui.team_selector = Team selector
|mdtx.ui.mark_mode_tap_the_screen_to_place_a_mark = [cyan]Mark mode: tap the screen to place a mark.
|mdtx.ui.view_recording_info = View recording info
|mdtx.ui.remove_logic_lock = Remove logic lock
|mdtx.ui.shortcut_scan_mode = S
|mdtx.ui.armor = [teal]Armor
|mdtx.ui.please_use_java_17_or_higher_to_run = ). Please use Java 17 or higher to run MindustryX. \n[grey]This warning cannot be disabled, please update Java.
|mdtx.ui.miner_ai = Miner AI
|mdtx.ui.the_map_has_arg_world_processors_arg_instruction_lines_and_arg_characters = The map has @ world processors, @ instruction lines, and @ characters.
|mdtx.ui.logic_camera_lock_removed = Logic camera lock removed
|mdtx.ui.build_area = Build area
|mdtx.ui.zoom_x = Zoom: x
|mdtx.ui.wave_settings = Wave Settings
|mdtx.ui.no_command_entered = No command entered
|mdtx.ui.block_rendering = Block Rendering
|mdtx.ui.builder_ai = Builder AI
|mdtx.ui.spawns_units_that_fly = [orange]spawns units that fly
|mdtx.ui.arc_message_center = ARC Message Center
|mdtx.ui.game_resumed = Game resumed
|mdtx.ui.selection_range = Selection Range
|mdtx.ui.select_code = Select Code
|mdtx.ui.tap_the_screen_to_capture_coordinates = [green]Tap the screen to capture coordinates
|mdtx.ui.this_is_a_message_from_mdtx = This is a message from MDTX-
|mdtx.ui.add_team = Add Team
|mdtx.ui.before_adding_new_instructions_please_save_the_edited_instructions_first = [yellow]Before adding new instructions, please save the edited instructions first.
|mdtx.ui.you_were_poked_please_pay_attention_to_the_information_box = [orange]You were poked. Please check the message dialog.
|mdtx.ui.global_range = Global range
|mdtx.ui.no_permission_to_edit_view_only = [yellow]No permission to edit; view only.
|mdtx.ui.cross = Cross
|mdtx.ui.shortcut_hitbox = H
|mdtx.ui.x_scan_speed = x scan speed
|mdtx.ui.display_name = Display name
|mdtx.ui.replay_not_loaded = Replay not loaded!
|mdtx.ui.updated_edited_logic = [orange]Updated edited logic!
|mdtx.ui.power = Power:
|mdtx.ui.unlock = Unlock
|mdtx.ui.cheat = Cheat
|mdtx.ui.player_build_range = Player build range
|mdtx.ui.damage = [red]Damage
|mdtx.ui.pick_up_payload = Pick up payload
|mdtx.ui.fx = FX
|mdtx.ui.share_unit_count = Share unit count
|mdtx.ui.upload_failed_try_again = Upload failed, try again?
|mdtx.ui.kotlin_language_standard_library = Kotlin language standard library
|mdtx.ui.ring = Ring
|mdtx.ui.command_mode = Command Mode
|mdtx.ui.force_boost = Force Boost
|mdtx.ui.permanent_status = <Permanent Status>
|mdtx.ui.frame_rate_simulation = Frame rate simulation
|mdtx.ui.lock_the_last_marked_point = Lock the last marked point
|mdtx.ui.effects_library = Effects Library
|mdtx.ui.share_inventory_status = Share inventory status
|mdtx.ui.server_msg = Server Msg
|mdtx.ui.size = Size:
|mdtx.ui.toggle = Toggle
|mdtx.ui.auto_refresh_variables = Auto-refresh variables
|mdtx.ui.vanilla = Vanilla
|mdtx.ui.no = No.
|mdtx.ui.fill_core_resources = Fill core resources
|mdtx.ui.force_skip_waves = Force skip waves
|mdtx.ui.event_wave = Event~Wave
|mdtx.ui.hide_logic_helper = Hide Logic Helper
|mdtx.ui.failed_to_create_replay = Failed to create replay!
|mdtx.ui.detached_camera = Detached camera
|mdtx.ui.squared = Squared
|mdtx.ui.add_panel = Add Panel
|mdtx.ui.add_destroyed_buildings_to_build_queue = Add destroyed buildings to build queue
|mdtx.ui.surrender_vote = Surrender Vote
|mdtx.ui.packet_count = Packet count:
|mdtx.ui.shortcut_block_render = B
|mdtx.ui.lightning_arg_probability_arg_damage_arg_length_arg_x_speed = Lightning @ probability ~ @ damage ~ @ length @x speed
|mdtx.ui.could_not_check_for_updates_nplease_try_again_later = Could not check for updates.\nPlease try again later.
|mdtx.ui.open_release_page = Open Release Page
|mdtx.ui.rules = Rules:
|mdtx.ui.replay_creation_time = Replay creation time:
|mdtx.ui.sec = sec
|mdtx.ui.copied_this_chat_record = Copied this chat record
|mdtx.ui.wall_shadow_rendering = Wall Shadow Rendering
|mdtx.ui.server_info_build = Server Info Build
|mdtx.ui.instant = Instant
|mdtx.ui.total_arg_arg_arg_arg_tile_radius = Total @@@~@ tile radius
|mdtx.ui.frame_rate_lock_mode_turned_off_ncurrent_game_speed_arg_times = Frame rate lock mode turned off \nCurrent game speed: @ times
|mdtx.ui.spawn_team = Spawn Team:
|mdtx.ui.share_power_status = Share power status
|mdtx.ui.logic_art_website = Logic art website
|mdtx.ui.contains_ground_x = Contains (ground x
|mdtx.ui.waves_suffix = waves,
|mdtx.ui.god_mode = God Mode
|mdtx.ui.single_player_map_tools_only = Single-player map tools only.
|mdtx.ui.spawn_location = Spawn location:
|mdtx.ui.mindustryx_version = MindustryX | Version
|mdtx.ui.repair_ai = Repair AI
|mdtx.ui.n_took_units = \n[white] took units:
|mdtx.ui.place_replace = Place/Replace
|mdtx.ui.effects_rendering = Effects Rendering
|mdtx.ui.rally = Rally
|mdtx.ui.download_and_install_update = Download and Install Update
|mdtx.ui.load_replay_file = Load replay file
|mdtx.ui.playback_version = Playback version:
|mdtx.ui.copied_variable_attributes_n_arg = Copied variable attributes\n@
|mdtx.ui.find_blocks = Find blocks
|mdtx.ui.paused = Paused
|mdtx.ui.hourglass = Hourglass:
|mdtx.ui.blueprint_code_link = Blueprint code link:
|mdtx.ui.template.atPlayer = <AT> poked {0}[white] to check their messages.
|mdtx.ui.template.atNoticeFrom = [gold]You were poked by [white]{0}[gold]! Check the message dialog.
|mdtx.ui.template.copiedMemory = [cyan]Copied memory[white]\n {0}
|mdtx.ui.template.currentVersion = Current version: {0}
|mdtx.ui.template.currentWave = *** Current wave: {0}
|mdtx.ui.template.introduction = Introduction: {0}
|mdtx.ui.template.failedReadImage = Failed to read image, please try another image\n{0}
|mdtx.ui.template.invalidBackgroundImage = Invalid background image: {0}
|mdtx.ui.template.exportCount = Successfully selected a total of {0} records:\n
|mdtx.ui.template.exportHeader = [MDTX-{0}] Exported in-game chat history
|mdtx.ui.template.labelWithEmoji = {0} {1}
|mdtx.ui.template.loadMap = Load map: {0}
|mdtx.ui.template.exportMap = *** Current map name: {0} (mode: {1})\n
|mdtx.ui.template.itemSelectionHeight = {0} rows
|mdtx.ui.template.itemSelectionWidth = {0} columns
|mdtx.ui.template.javaWarnDialog = Java version {0} is too low and unsupported.\n[grey]This warning cannot be disabled; please update Java.
|mdtx.ui.template.javaWarnLog = Java version {0} is too low and unsupported. Please use Java 17+ to run MindustryX.
|mdtx.ui.template.newVersion = [green]New version found[]: {0}
|mdtx.ui.template.savedBlueprint = Saved blueprint: {0}
|mdtx.ui.template.windowTitle = MindustryX | Version {0} | mods enabled {1}/{2}
|mdtx.ui.template.shareHeader = This is a share log from MDTX-{0}\n
|mdtx.ui.template.shareCode = <ARCxMDTX><Schem>[black]compat code[] {0}
|mdtx.ui.template.toggleState = {0}: {1}
|mdtx.ui.template.waveEvent = Waves: {0} | {1}
|mdtx.ui.template.waveContains = Contains (ground x{0}, air x{1}):
|mdtx.ui.template.waveEta = (in {0} waves, {1})
|mdtx.ui.template.waveTitle = Wave {0}
|
""".trimMargin()
}
