@file:JvmName("FuncX")
@file:JvmMultifileClass

package mindustryX.bundles

import arc.Core
import java.util.Locale

private val uiTextsZh = mapOf(
    "add_destroyed_buildings_to_build_queue" to "在建造列表加入被摧毁建筑" ,
    "add_panel" to "添加面板" ,
    "add_prefix_t" to "前缀添加/t" ,
    "add_team" to "添加队伍" ,
    "air_only" to "仅对空" ,
    "air_x" to ",空x" ,
    "all" to "全部" ,
    "all_players" to "全部玩家" ,
    "allowed_range_2_9999" to "允许的范围：2~9999" ,
    "always_on" to "一直开启" ,
    "arc_ai_configurator" to "ARC-AI设定器" ,
    "arc_image_converter" to "arc-图片转换器" ,
    "arc_message_center" to "ARC-中央监控室" ,
    "arc_ore_statistics" to "ARC-矿物统计" ,
    "arg_arg_ndistance_arg" to "@,@\\n距离: @" ,
    "arg_s_arg_tiles" to "@s~@格" ,
    "arg_shield_capacity_arg_grid_arg_recovery_arg_s_cooldown" to "@盾容~@格~@恢复~@s冷却" ,
    "armor" to "[teal]装甲" ,
    "artboard" to "画板++" ,
    "attack" to "攻击" ,
    "attack_no_border" to "攻击去边框" ,
    "attack_speed" to "[violet]攻速" ,
    "auto_attack" to "自动攻击" ,
    "auto_fill" to "一键装填" ,
    "auto_refresh_variables" to "变量自动更新" ,
    "automatically_refresh_variables" to "自动刷新变量" ,
    "automatically_save_as_blueprint" to "自动保存为蓝图" ,
    "basic" to "基础对比" ,
    "before_adding_new_instructions_please_save_the_edited_instructions_first" to "[yellow]添加新指令前，请先保存编辑的指令" ,
    "below_is_mdtx" to "下面是[MDTX-" ,
    "block_rendering" to "建筑显示" ,
    "blueprint_code_link" to "蓝图代码链接：" ,
    "blueprint_code_n" to "蓝图代码：\\n" ,
    "blueprint_cost" to "蓝图造价：" ,
    "blueprint_name" to "蓝图名：" ,
    "build_area" to "建造区域" ,
    "build_speed" to "[accent]建速" ,
    "builder_ai" to "重建AI" ,
    "buildings" to "建筑：" ,
    "built_in_prefix" to "[内置]" ,
    "bullet_rendering" to "子弹显示" ,
    "cancel" to "取消" ,
    "canvas" to "画板" ,
    "carried_item" to "携带物品:" ,
    "chat" to "聊天" ,
    "chat_history_exceeding_the_limit_will_be_cleared_when_loading_the_map" to "超出限制的聊天记录将在载入地图时清除" ,
    "cheat" to "无限火力" ,
    "check_for_updates" to "自动更新" ,
    "clear" to "清空" ,
    "clear_all_core_resources" to "清空核心的所有资源" ,
    "click_the_screen_to_return" to "[green]点击屏幕返回" ,
    "clone" to "克隆" ,
    "color" to "颜色" ,
    "command" to "指令" ,
    "command_mode" to "指挥模式" ,
    "construction_suspended" to "暂停建造" ,
    "contains_ground_x" to "包含(地×" ,
    "copied_print_buffer_n_arg" to "复制信息版\\n@" ,
    "copied_successfully" to "复制成功:" ,
    "copied_this_chat_record" to "已导出本条聊天记录" ,
    "copied_variable_attributes_n_arg" to "复制变量属性\\n@" ,
    "copied_variable_name_n_arg" to "复制变量名\\n@" ,
    "could_not_check_for_updates_nplease_try_again_later" to "检查更新失败，请稍后再试" ,
    "cross" to "十字" ,
    "current_frame_rate_locked_arg" to "当前帧率锁定：@" ,
    "current_game_speed_arg_times" to "当前游戏速度：@倍" ,
    "current_map_arg" to "当前地图:@" ,
    "current_map_name" to "*** 当前地图名称:" ,
    "current_selection_is_empty_select_a_block_in_the_inventory" to "[yellow]当前选中物品为空，请在物品栏选中建筑" ,
    "current_unit_cannot_build" to "[red]当前单位不可建筑" ,
    "damage" to "[red]伤害" ,
    "defender_ai" to "保护AI" ,
    "detached_camera" to "视角脱离玩家" ,
    "display_name" to "显示名" ,
    "download_and_install_update" to "自动下载更新" ,
    "drop_payload" to "丢下载荷" ,
    "each_cell_absorbs_arg_s_arg_arg_arg_s_and_returns_blood_maximum_arg_s" to "每格吸收@/s@@~@/s回血~最大@/s" ,
    "editor" to "编辑器" ,
    "effects_library" to "特效大全" ,
    "effects_rendering" to "特效显示" ,
    "empty_selection_area_hint" to "当前选定区域为空，请通过F规划区域" ,
    "enter_the_conveyor_belt" to "进入传送带" ,
    "event_map_load" to "事件~载入地图" ,
    "event_wave" to "事件~波次" ,
    "export" to "导出" ,
    "export_chat_history" to "导出聊天记录" ,
    "exported_in_game_chat_history" to "] 导出的游戏内聊天记录" ,
    "extract_code_from_schematic" to "从蓝图中选择代码" ,
    "failed_to_create_replay" to "创建回放出错!" ,
    "failed_to_read_image_please_try_another_image_n" to "读取图片失败，请尝试更换图片\\n" ,
    "failed_to_read_playback" to "读取回放失败!" ,
    "fill_core_resources" to "填满核心的所有资源" ,
    "find_blocks" to "查找方块" ,
    "fixed_size" to "固定大小" ,
    "flash_on_change" to "变动闪烁" ,
    "flash_on_variable_change" to "变量变动闪烁" ,
    "flight_mode" to "飞行模式" ,
    "fog_of_war" to "战争迷雾" ,
    "force_boost" to "强制助推" ,
    "force_skip_waves" to "强制跳波" ,
    "frame_rate_lock_mode_enabled_ncurrent_frame_rate_lock_arg" to "已开启帧率锁定模式\\n当前帧率锁定：@" ,
    "frame_rate_lock_mode_turned_off_ncurrent_game_speed_arg_times" to "已关闭帧率锁定模式\\n当前游戏速度：@倍" ,
    "frame_rate_simulation" to "帧率模拟" ,
    "fx" to "效" ,
    "game_resumed" to "已继续游戏" ,
    "generate_quantity" to "生成数量:" ,
    "generated_label" to "[orange]已" ,
    "global_range" to "全局检查" ,
    "god_mode" to "创世神" ,
    "ground_only" to "仅对地" ,
    "health_label" to "[red]血量：" ,
    "hide_all_buildings" to "隐藏全部建筑" ,
    "hide_logic_helper" to "隐藏逻辑辅助器" ,
    "hitbox_overlay" to "碰撞箱显示" ,
    "hourglass" to "沙漏：" ,
    "hp" to "[acid]血量" ,
    "hue_mode" to "色调函数:" ,
    "icon" to "图标" ,
    "index" to "序号" ,
    "instant" to "瞬间完成" ,
    "item" to "物品" ,
    "kotlin_language_standard_library" to "Kotlin语言标准库" ,
    "lightning_arg_probability_arg_damage_arg_length_arg_x_speed" to "闪电@概率~@伤害~@长度 @x速度" ,
    "liquids" to "液体" ,
    "load_building" to "装载建筑" ,
    "load_map" to "载入地图：" ,
    "load_replay_file" to "加载回放文件" ,
    "load_self" to "装载自己" ,
    "load_unit" to "装载单位" ,
    "lock" to "锁定" ,
    "lock_the_last_marked_point" to "锁定上个标记点" ,
    "logic_announcement" to "逻辑~公告" ,
    "logic_art_website" to "逻辑画网站" ,
    "logic_camera_lock_removed" to "已移除逻辑视角锁定" ,
    "logic_helper_x" to "逻辑辅助器[gold]X[]" ,
    "logic_notice" to "逻辑~通报" ,
    "mark_coordinates" to "标记~坐标" ,
    "mark_map_location" to "标记地图位置" ,
    "mark_mode_tap_the_screen_to_place_a_mark" to "[cyan]标记模式,点击屏幕标记." ,
    "mark_player" to "标记~玩家" ,
    "maximum_storage_of_chat_history_too_high_may_cause_lag" to "最大储存聊天记录(过高可能导致卡顿)：" ,
    "message_arg_js_starts_with_script" to "消息(@js 开头为脚本)" ,
    "message_center" to "中央监控室" ,
    "mindustryx_version" to "MindustryX | 版本号" ,
    "miner_ai" to "矿机AI" ,
    "miner_ai_ore_filter" to "minerAI-矿物筛选器" ,
    "minimap" to "小地图显示" ,
    "mods_enabled" to "| mod启用" ,
    "more_teams" to "更多队伍选择" ,
    "movement_speed" to "[cyan]移速" ,
    "n_took_units" to "\\n[white]分走了单位:" ,
    "name" to "名称" ,
    "no" to "第" ,
    "no_command_entered" to "未输入指令" ,
    "no_permission_to_edit_view_only" to "[yellow]当前无权编辑，仅供查阅" ,
    "observer_mode" to "观察者模式" ,
    "off" to "关闭" ,
    "on" to "开启" ,
    "open_playback_file" to "打开回放文件" ,
    "open_release_page" to "打开发布页面" ,
    "ore_count_surface_wall" to "矿物矿(地表/墙矿)" ,
    "ore_info" to "矿物信息" ,
    "original_size" to "原始大小" ,
    "packet_count" to "数据包总数：" ,
    "panels_currently_unavailable" to "当前不可用的面板:" ,
    "path" to "路径" ,
    "pause_logic_game_execution" to "暂停逻辑(游戏)运行" ,
    "pause_time" to "暂停时间" ,
    "paused" to "已暂停" ,
    "permanent_status" to "<永久状态>" ,
    "pick_up_payload" to "捡起载荷" ,
    "pixel_art" to "像素画" ,
    "place_replace" to "放置/替换" ,
    "placeholder_x" to "倍" ,
    "playback_length" to "回放长度:" ,
    "playback_version" to "回放版本:" ,
    "player_build_range" to "玩家建造区" ,
    "player_name" to "玩家名:" ,
    "please_don_t_tag_too_often" to "请不要频繁标记!" ,
    "please_use_java_17_or_higher_to_run" to ")。请使用Java 17或更高版本运行MindustryX。\\n[grey]该警告不存在设置，请更新Java版本。" ,
    "poked_you_check_the_message_dialog" to "[gold]戳了一下，请注意查看信息框哦~" ,
    "power" to "电力：" ,
    "preview_releases_n_faster_updates_new_features_bug_fixes" to "预览版(更新更快,新功能体验,BUG修复)" ,
    "radar_scanning" to ">> 雷达扫描中 <<" ,
    "radar_toggle" to "雷达开关" ,
    "rally" to "集合" ,
    "randomly_generated_within_this_range_near_the_target_point" to "在目标点附近的这个范围内随机生成" ,
    "recording_arg" to "录制中: @" ,
    "recording_ended" to "录制结束" ,
    "recording_error" to "录制出错!" ,
    "refresh_edited_logic" to "更新编辑的逻辑" ,
    "refresh_interval" to "刷新间隔" ,
    "release_notes" to "发布说明" ,
    "remove_logic_lock" to "移除逻辑锁定" ,
    "repair_ai" to "修复AI" ,
    "replay_creation_time" to "回放创建时间:" ,
    "replay_not_loaded" to "未加载回放!" ,
    "replay_stats" to "回放统计" ,
    "reset" to "重置" ,
    "reset_all_links" to "重置所有链接" ,
    "resistance" to "[purple]阻力" ,
    "restore_current_wave" to "恢复当前波次" ,
    "return_to_original_speed" to "恢复原速" ,
    "ring" to "虚圆" ,
    "ring_cross" to "圆十字" ,
    "rules" to "规则：" ,
    "sandbox" to "沙盒" ,
    "saved_to_clipboard" to "已保存至剪贴板" ,
    "scaled_size" to "缩放后大小" ,
    "scan_mode" to "扫描模式" ,
    "sec" to "秒" ,
    "select_and_import_pictures_which_can_be_converted" to "选择并导入图片，可将其转成画板、像素画或是逻辑画" ,
    "select_code" to "选择代码" ,
    "select_image_png" to "选择图片[white](png)" ,
    "selection_range" to "选择范围" ,
    "self_destruct" to "自杀" ,
    "server_info_build" to "服务器信息版" ,
    "server_ip" to "服务器ip:" ,
    "server_msg" to "服务器信息" ,
    "set_target" to "设置目标" ,
    "set_target_wave" to "设定查询波次" ,
    "share_inventory_status" to "分享库存情况" ,
    "share_power_status" to "分享电力情况" ,
    "share_unit_count" to "分享单位数量" ,
    "share_wave_information" to "分享波次信息" ,
    "shared_by" to "分享者：" ,
    "shield" to "[yellow]护盾：" ,
    "shortcut_block_render" to "块" ,
    "shortcut_bullet_render" to "弹" ,
    "shortcut_fog" to "雾" ,
    "shortcut_hitbox" to "箱" ,
    "shortcut_message_center" to "信" ,
    "shortcut_observer_mode" to "观" ,
    "shortcut_scan_mode" to "扫" ,
    "shortcut_server_info" to "版" ,
    "shortcut_surrender_vote" to "[white]法" ,
    "shortcut_unit_render" to "兵" ,
    "shortcut_wall_shadow" to "墙" ,
    "show_all" to "全部显示" ,
    "show_all_message_blocks" to "信息板全显示" ,
    "show_building_status_only" to "只显示建筑状态" ,
    "single_player_map_tools_only" to "警告：该页功能主要供单机作图使用" ,
    "size" to "大小：" ,
    "slow_the_flow_of_time_to_half" to "将时间流速放慢到一半" ,
    "spawn_location" to "生成位置:" ,
    "spawn_range" to "生成范围：" ,
    "spawn_team" to "生成队伍:" ,
    "spawned" to "[orange]生成！" ,
    "spawns_units_that_fly" to "[orange]生成的单位会飞起来" ,
    "speed_up_time_to_2x" to "将时间流速加快到两倍" ,
    "squared" to "平方对比" ,
    "stable_releases" to "正式版" ,
    "staging_area" to "暂存区" ,
    "successfully_selected_a_total_of" to "成功选取共" ,
    "surrender_vote" to "法国军礼" ,
    "surrender_vote_confirm" to "受不了，直接投降？" ,
    "sync_a_wave" to "同步一波" ,
    "tap_the_screen_to_capture_coordinates" to "[green]点击屏幕采集坐标" ,
    "team" to "队伍：" ,
    "team_id" to "队伍ID:" ,
    "team_range" to "队伍区域" ,
    "team_selector" to "队伍选择器" ,
    "template.atNoticeFrom" to "[gold]你被[white]{0}[gold]戳了一下，请注意查看信息框哦~" ,
    "template.atPlayer" to "<AT>戳了{0}[white]一下，并提醒他留意对话框" ,
    "template.copiedMemory" to "[cyan]复制内存[white]\\n {0}" ,
    "template.currentVersion" to "当前版本号: {0}" ,
    "template.currentWave" to "*** 当前波次: {0}" ,
    "template.exportCount" to "成功选取共{0}条记录，如下：\\n" ,
    "template.exportHeader" to "下面是[MDTX-{0}] 导出的游戏内聊天记录" ,
    "template.exportMap" to "*** 当前地图名称: {0}(模式: {1})\\n" ,
    "template.failedReadImage" to "读取图片失败，请尝试更换图片\\n{0}" ,
    "template.introduction" to "简介：{0}" ,
    "template.invalidBackgroundImage" to "背景图片无效: {0}" ,
    "template.itemSelectionHeight" to "{0} 行" ,
    "template.itemSelectionWidth" to "{0} 列" ,
    "template.javaWarnDialog" to "Java版本 {0} 过低，不受支持。\\n[grey]该警告不存在设置，请更新Java版本。" ,
    "template.javaWarnLog" to "Java版本 {0} 过低，不受支持。请使用Java 17或更高版本运行MindustryX。" ,
    "template.labelWithEmoji" to "{0} {1}" ,
    "template.loadMap" to "载入地图：{0}" ,
    "template.newVersion" to "[green]发现新版本[]: {0}" ,
    "template.savedBlueprint" to "已保存蓝图：{0}" ,
    "template.shareCode" to "<ARCxMDTX><Schem>[black]一坨兼容[] {0}" ,
    "template.shareHeader" to "这是一条来自 MDTX-{0} 的分享记录\\n" ,
    "template.toggleState" to "{0}: {1}" ,
    "template.waveContains" to "包含(地×{0},空x{1}):" ,
    "template.waveEta" to "(还有{0}波, {1})" ,
    "template.waveEvent" to "波次：{0} | {1}" ,
    "template.waveTitle" to "第{0}波" ,
    "template.windowTitle" to "MindustryX | 版本号 {0} | mod启用{1}/{2}" ,
    "temporary_status" to "<瞬间状态>" ,
    "terrain_blueprint" to "地形蓝图" ,
    "the_blueprint_code_is_too_long_please_click_the_link_to_view_it" to "蓝图代码过长，请点击链接查看" ,
    "the_map_has_arg_world_processors_arg_instruction_lines_and_arg_characters" to "地图共有@个世处，总共@行指令，@个字符" ,
    "there_are_no_enemies_in_this_wave" to "该波次没有敌人" ,
    "there_are_too_many_buildings_to_avoid_lag_and_only_keep_the_first_1000_plans" to "[yellow]建筑过多，避免卡顿，仅保留前1000个规划" ,
    "this_is_a_cheat_feature_njump_to_the" to "[red]这是一个作弊功能[]\\n快速跳转到目标波次(不刷兵)" ,
    "this_is_a_message_from_mdtx" to "这是一条来自 MDTX-" ,
    "tiles" to "格" ,
    "tip_all_schematics_containing_processors" to "TIP: 所有包含处理器的蓝图" ,
    "toggle" to "开关" ,
    "toggle_your_team_s_cheat" to "开关自己队的无限火力" ,
    "total_arg_arg_arg_arg_tile_radius" to "总计@@@~@格半径" ,
    "ui_icon_library" to "UI图标大全" ,
    "ui_toolkit" to "ui大全" ,
    "unique" to "独一无二" ,
    "unit" to "单位：" ,
    "unit_factory" to "单位工厂" ,
    "unit_factory_x" to "单位工厂-X" ,
    "unit_rendering" to "兵种显示" ,
    "unlimited" to "无限制" ,
    "unlock" to "解禁" ,
    "unlock_and_allow_all_blocks" to "显示并允许建造所有物品" ,
    "updated_edited_logic" to "[orange]已更新编辑的逻辑！" ,
    "upload_failed_try_again" to "上传失败，再重试一下？" ,
    "vanilla" to "原版" ,
    "view_recording_info" to "查看录制信息" ,
    "wall_shadow_rendering" to "墙体阴影显示" ,
    "warning_image_may_be_too_large_please_try_compressing_image" to "[orange]警告：图片可能过大，请尝试压缩图片" ,
    "wave" to "波" ,
    "wave_in_prefix" to "还有" ,
    "wave_info" to "波次信息" ,
    "wave_settings" to "波次设定" ,
    "waves" to "波次：" ,
    "waves_suffix" to "波," ,
    "x_scan_speed" to "倍搜索速度" ,
    "you_are_already_on_the_latest_version" to "你已是最新版本，不需要更新！" ,
    "you_were_poked_please_pay_attention_to_the_information_box" to "[orange]你被戳了一下，请注意查看信息框哦~" ,
    "zoom" to "缩放" ,
    "zoom_x" to "缩放: x" ,
    "zoom_zoom" to "缩放: " ,
)

private val uiTextsEn = mapOf(
    "add_destroyed_buildings_to_build_queue" to "Add destroyed buildings to build queue" ,
    "add_panel" to "Add Panel" ,
    "add_prefix_t" to "Add prefix /t" ,
    "add_team" to "Add Team" ,
    "air_only" to "Air only" ,
    "air_x" to ", air x" ,
    "all" to "All" ,
    "all_players" to "All players" ,
    "allowed_range_2_9999" to "Allowed range: 2~9999" ,
    "always_on" to "Always On" ,
    "arc_ai_configurator" to "ARC-AI Configurator" ,
    "arc_image_converter" to "ARC Image Converter" ,
    "arc_message_center" to "ARC Message Center" ,
    "arc_ore_statistics" to "ARC Ore Statistics" ,
    "arg_arg_ndistance_arg" to "@,@\\nDistance: @" ,
    "arg_s_arg_tiles" to "@s~@ tiles" ,
    "arg_shield_capacity_arg_grid_arg_recovery_arg_s_cooldown" to "@ shield capacity ~ @ grid ~ @ recovery ~ @s cooldown" ,
    "armor" to "[teal]Armor" ,
    "artboard" to "Artboard++" ,
    "attack" to "Attack" ,
    "attack_no_border" to "Attack (no border)" ,
    "attack_speed" to "[violet]Attack speed" ,
    "auto_attack" to "Auto Attack" ,
    "auto_fill" to "Auto Fill" ,
    "auto_refresh_variables" to "Auto-refresh variables" ,
    "automatically_refresh_variables" to "Automatically refresh variables" ,
    "automatically_save_as_blueprint" to "Automatically save as blueprint" ,
    "basic" to "Basic" ,
    "before_adding_new_instructions_please_save_the_edited_instructions_first" to "[yellow]Before adding new instructions, please save the edited instructions first." ,
    "below_is_mdtx" to "Below is [MDTX-" ,
    "block_rendering" to "Block Rendering" ,
    "blueprint_code_link" to "Blueprint code link:" ,
    "blueprint_code_n" to "Blueprint code: \\n" ,
    "blueprint_cost" to "Blueprint cost:" ,
    "blueprint_name" to "Blueprint name:" ,
    "build_area" to "Build area" ,
    "build_speed" to "[accent]Build Speed" ,
    "builder_ai" to "Builder AI" ,
    "buildings" to "Buildings:" ,
    "built_in_prefix" to "[Built-in]" ,
    "bullet_rendering" to "Bullet Rendering" ,
    "cancel" to "Cancel" ,
    "canvas" to "Canvas" ,
    "carried_item" to "Carried item:" ,
    "chat" to "Chat" ,
    "chat_history_exceeding_the_limit_will_be_cleared_when_loading_the_map" to "Chat history exceeding the limit will be cleared when loading the map" ,
    "cheat" to "Cheat" ,
    "check_for_updates" to "Check for Updates" ,
    "clear" to "Clear" ,
    "clear_all_core_resources" to "Clear all core resources" ,
    "click_the_screen_to_return" to "[green]Click the screen to return" ,
    "clone" to "Clone" ,
    "color" to "Color" ,
    "command" to "Command" ,
    "command_mode" to "Command Mode" ,
    "construction_suspended" to "Construction suspended" ,
    "contains_ground_x" to "Contains (ground x" ,
    "copied_print_buffer_n_arg" to "Copied print buffer\\n@" ,
    "copied_successfully" to "Copied successfully:" ,
    "copied_this_chat_record" to "Copied this chat record" ,
    "copied_variable_attributes_n_arg" to "Copied variable attributes\\n@" ,
    "copied_variable_name_n_arg" to "Copied variable name\\n@" ,
    "could_not_check_for_updates_nplease_try_again_later" to "Could not check for updates.\\nPlease try again later." ,
    "cross" to "Cross" ,
    "current_frame_rate_locked_arg" to "Current frame rate locked: @" ,
    "current_game_speed_arg_times" to "Current game speed: @ times" ,
    "current_map_arg" to "Current map: @" ,
    "current_map_name" to "*** Current map name:" ,
    "current_selection_is_empty_select_a_block_in_the_inventory" to "[yellow]Current selection is empty; select a block in the inventory." ,
    "current_unit_cannot_build" to "[red]Current unit cannot build" ,
    "damage" to "[red]Damage" ,
    "defender_ai" to "Defender AI" ,
    "detached_camera" to "Detached camera" ,
    "display_name" to "Display name" ,
    "download_and_install_update" to "Download and Install Update" ,
    "drop_payload" to "Drop Payload" ,
    "each_cell_absorbs_arg_s_arg_arg_arg_s_and_returns_blood_maximum_arg_s" to "Each cell absorbs @/s@@~heals @/s~up to @/s" ,
    "editor" to "Editor" ,
    "effects_library" to "Effects Library" ,
    "effects_rendering" to "Effects Rendering" ,
    "empty_selection_area_hint" to "The currently selected area is empty. Please use F to plan the area." ,
    "enter_the_conveyor_belt" to "Enter the conveyor belt" ,
    "event_map_load" to "Event~Map Load" ,
    "event_wave" to "Event~Wave" ,
    "export" to "Export" ,
    "export_chat_history" to "Export chat history" ,
    "exported_in_game_chat_history" to "] Exported in-game chat history" ,
    "extract_code_from_schematic" to "Extract code from schematic" ,
    "failed_to_create_replay" to "Failed to create replay!" ,
    "failed_to_read_image_please_try_another_image_n" to "Failed to read image, please try another image\\n" ,
    "failed_to_read_playback" to "Failed to read playback!" ,
    "fill_core_resources" to "Fill core resources" ,
    "find_blocks" to "Find blocks" ,
    "fixed_size" to "Fixed size" ,
    "flash_on_change" to "Flash on Change" ,
    "flash_on_variable_change" to "Flash on variable change" ,
    "flight_mode" to "Flight mode" ,
    "fog_of_war" to "Fog of War" ,
    "force_boost" to "Force Boost" ,
    "force_skip_waves" to "Force skip waves" ,
    "frame_rate_lock_mode_enabled_ncurrent_frame_rate_lock_arg" to "Frame rate lock mode enabled \\nCurrent frame rate lock: @" ,
    "frame_rate_lock_mode_turned_off_ncurrent_game_speed_arg_times" to "Frame rate lock mode turned off \\nCurrent game speed: @ times" ,
    "frame_rate_simulation" to "Frame rate simulation" ,
    "fx" to "FX" ,
    "game_resumed" to "Game resumed" ,
    "generate_quantity" to "Generate quantity:" ,
    "generated_label" to "Generated" ,
    "global_range" to "Global range" ,
    "god_mode" to "God Mode" ,
    "ground_only" to "Ground only" ,
    "health_label" to "[red]HP:" ,
    "hide_all_buildings" to "Hide all buildings" ,
    "hide_logic_helper" to "Hide Logic Helper" ,
    "hitbox_overlay" to "Hitbox Overlay" ,
    "hourglass" to "Hourglass:" ,
    "hp" to "[acid]HP" ,
    "hue_mode" to "Hue mode:" ,
    "icon" to "Icon" ,
    "index" to "Index" ,
    "instant" to "Instant" ,
    "item" to "Item" ,
    "kotlin_language_standard_library" to "Kotlin language standard library" ,
    "lightning_arg_probability_arg_damage_arg_length_arg_x_speed" to "Lightning @ probability ~ @ damage ~ @ length @x speed" ,
    "liquids" to "Liquids" ,
    "load_building" to "Load Building" ,
    "load_map" to "Load map:" ,
    "load_replay_file" to "Load replay file" ,
    "load_self" to "Load self" ,
    "load_unit" to "Load Unit" ,
    "lock" to "Lock" ,
    "lock_the_last_marked_point" to "Lock the last marked point" ,
    "logic_announcement" to "Logic~Announcement" ,
    "logic_art_website" to "Logic art website" ,
    "logic_camera_lock_removed" to "Logic camera lock removed" ,
    "logic_helper_x" to "Logic Helper[gold]X[]" ,
    "logic_notice" to "Logic~Notice" ,
    "mark_coordinates" to "Mark~Coordinates" ,
    "mark_map_location" to "Mark map location" ,
    "mark_mode_tap_the_screen_to_place_a_mark" to "[cyan]Mark mode: tap the screen to place a mark." ,
    "mark_player" to "Mark~Player" ,
    "maximum_storage_of_chat_history_too_high_may_cause_lag" to "Maximum storage of chat history (too high may cause lag):" ,
    "message_arg_js_starts_with_script" to "Message (@js starts with script)" ,
    "message_center" to "Message Center" ,
    "mindustryx_version" to "MindustryX | Version" ,
    "miner_ai" to "Miner AI" ,
    "miner_ai_ore_filter" to "Miner AI - Ore Filter" ,
    "minimap" to "Minimap" ,
    "mods_enabled" to "| mods enabled" ,
    "more_teams" to "More Teams" ,
    "movement_speed" to "[cyan]Movement speed" ,
    "n_took_units" to "\\n[white] took units:" ,
    "name" to "Name" ,
    "no" to "No." ,
    "no_command_entered" to "No command entered" ,
    "no_permission_to_edit_view_only" to "[yellow]No permission to edit; view only." ,
    "observer_mode" to "Observer Mode" ,
    "off" to "Off" ,
    "on" to "On" ,
    "open_playback_file" to "Open playback file" ,
    "open_release_page" to "Open Release Page" ,
    "ore_count_surface_wall" to "Ore Count (surface/wall)" ,
    "ore_info" to "Ore Info" ,
    "original_size" to "Original size" ,
    "packet_count" to "Packet count:" ,
    "panels_currently_unavailable" to "Panels currently unavailable:" ,
    "path" to "Path" ,
    "pause_logic_game_execution" to "Pause logic (game) execution" ,
    "pause_time" to "Pause time" ,
    "paused" to "Paused" ,
    "permanent_status" to "<Permanent Status>" ,
    "pick_up_payload" to "Pick up payload" ,
    "pixel_art" to "Pixel Art" ,
    "place_replace" to "Place/Replace" ,
    "placeholder_x" to "x" ,
    "playback_length" to "Playback length:" ,
    "playback_version" to "Playback version:" ,
    "player_build_range" to "Player build range" ,
    "player_name" to "Player name:" ,
    "please_don_t_tag_too_often" to "Please don't tag too often!" ,
    "please_use_java_17_or_higher_to_run" to "). Please use Java 17 or higher to run MindustryX. \\n[grey]This warning cannot be disabled, please update Java." ,
    "poked_you_check_the_message_dialog" to "[gold]You were poked; check the message dialog." ,
    "power" to "Power:" ,
    "preview_releases_n_faster_updates_new_features_bug_fixes" to "Preview Releases\\n(faster updates, new features, bug fixes)" ,
    "radar_scanning" to ">> Radar Scanning <<" ,
    "radar_toggle" to "Radar Toggle" ,
    "rally" to "Rally" ,
    "randomly_generated_within_this_range_near_the_target_point" to "Randomly generated within this range near the target point" ,
    "recording_arg" to "Recording: @" ,
    "recording_ended" to "Recording ended" ,
    "recording_error" to "Recording error!" ,
    "refresh_edited_logic" to "Refresh edited logic" ,
    "refresh_interval" to "Refresh interval" ,
    "release_notes" to "Release Notes" ,
    "remove_logic_lock" to "Remove logic lock" ,
    "repair_ai" to "Repair AI" ,
    "replay_creation_time" to "Replay creation time:" ,
    "replay_not_loaded" to "Replay not loaded!" ,
    "replay_stats" to "Replay Stats" ,
    "reset" to "Reset" ,
    "reset_all_links" to "Reset all links" ,
    "resistance" to "[purple]Resistance" ,
    "restore_current_wave" to "Restore current wave" ,
    "return_to_original_speed" to "Return to original speed" ,
    "ring" to "Ring" ,
    "ring_cross" to "Ring Cross" ,
    "rules" to "Rules:" ,
    "sandbox" to "Sandbox" ,
    "saved_to_clipboard" to "Saved to clipboard" ,
    "scaled_size" to "Scaled size" ,
    "scan_mode" to "Scan Mode" ,
    "sec" to "sec" ,
    "select_and_import_pictures_which_can_be_converted" to "Select and import pictures, which can be converted into artboards, pixel paintings or logic paintings." ,
    "select_code" to "Select Code" ,
    "select_image_png" to "Select image[white](png)" ,
    "selection_range" to "Selection Range" ,
    "self_destruct" to "Self-Destruct" ,
    "server_info_build" to "Server Info Build" ,
    "server_ip" to "Server IP:" ,
    "server_msg" to "Server Msg" ,
    "set_target" to "Set target" ,
    "set_target_wave" to "Set target wave" ,
    "share_inventory_status" to "Share inventory status" ,
    "share_power_status" to "Share power status" ,
    "share_unit_count" to "Share unit count" ,
    "share_wave_information" to "Share wave information" ,
    "shared_by" to "Shared by:" ,
    "shield" to "[yellow]Shield:" ,
    "shortcut_block_render" to "B" ,
    "shortcut_bullet_render" to "P" ,
    "shortcut_fog" to "F" ,
    "shortcut_hitbox" to "H" ,
    "shortcut_message_center" to "M" ,
    "shortcut_observer_mode" to "O" ,
    "shortcut_scan_mode" to "S" ,
    "shortcut_server_info" to "V" ,
    "shortcut_surrender_vote" to "[white]S" ,
    "shortcut_unit_render" to "U" ,
    "shortcut_wall_shadow" to "W" ,
    "show_all" to "Show all" ,
    "show_all_message_blocks" to "Show all message blocks" ,
    "show_building_status_only" to "Show building status only" ,
    "single_player_map_tools_only" to "Single-player map tools only." ,
    "size" to "Size:" ,
    "slow_the_flow_of_time_to_half" to "Slow the flow of time to half" ,
    "spawn_location" to "Spawn location:" ,
    "spawn_range" to "Spawn range:" ,
    "spawn_team" to "Spawn Team:" ,
    "spawned" to "[orange]spawned!" ,
    "spawns_units_that_fly" to "[orange]spawns units that fly" ,
    "speed_up_time_to_2x" to "Speed up time to 2x" ,
    "squared" to "Squared" ,
    "stable_releases" to "Stable Releases" ,
    "staging_area" to "Staging area" ,
    "successfully_selected_a_total_of" to "Successfully selected a total of" ,
    "surrender_vote" to "Surrender Vote" ,
    "surrender_vote_confirm" to "Are you sure you want to surrender?" ,
    "sync_a_wave" to "Sync a wave" ,
    "tap_the_screen_to_capture_coordinates" to "[green]Tap the screen to capture coordinates" ,
    "team" to "Team:" ,
    "team_id" to "Team ID:" ,
    "team_range" to "Team range" ,
    "team_selector" to "Team selector" ,
    "template.atNoticeFrom" to "[gold]You were poked by [white]{0}[gold]! Check the message dialog." ,
    "template.atPlayer" to "<AT> poked {0}[white] to check their messages." ,
    "template.copiedMemory" to "[cyan]Copied memory[white]\\n {0}" ,
    "template.currentVersion" to "Current version: {0}" ,
    "template.currentWave" to "*** Current wave: {0}" ,
    "template.exportCount" to "Successfully selected a total of {0} records:\\n" ,
    "template.exportHeader" to "[MDTX-{0}] Exported in-game chat history" ,
    "template.exportMap" to "*** Current map name: {0} (mode: {1})\\n" ,
    "template.failedReadImage" to "Failed to read image, please try another image\\n{0}" ,
    "template.introduction" to "Introduction: {0}" ,
    "template.invalidBackgroundImage" to "Invalid background image: {0}" ,
    "template.itemSelectionHeight" to "{0} rows" ,
    "template.itemSelectionWidth" to "{0} columns" ,
    "template.javaWarnDialog" to "Java version {0} is too low and unsupported.\\n[grey]This warning cannot be disabled; please update Java." ,
    "template.javaWarnLog" to "Java version {0} is too low and unsupported. Please use Java 17+ to run MindustryX." ,
    "template.labelWithEmoji" to "{0} {1}" ,
    "template.loadMap" to "Load map: {0}" ,
    "template.newVersion" to "[green]New version found[]: {0}" ,
    "template.savedBlueprint" to "Saved blueprint: {0}" ,
    "template.shareCode" to "<ARCxMDTX><Schem>[black]compat code[] {0}" ,
    "template.shareHeader" to "This is a share log from MDTX-{0}\\n" ,
    "template.toggleState" to "{0}: {1}" ,
    "template.waveContains" to "Contains (ground x{0}, air x{1}):" ,
    "template.waveEta" to "(in {0} waves, {1})" ,
    "template.waveEvent" to "Waves: {0} | {1}" ,
    "template.waveTitle" to "Wave {0}" ,
    "template.windowTitle" to "MindustryX | Version {0} | mods enabled {1}/{2}" ,
    "temporary_status" to "<Temporary State>" ,
    "terrain_blueprint" to "Terrain Blueprint" ,
    "the_blueprint_code_is_too_long_please_click_the_link_to_view_it" to "The blueprint code is too long, please click the link to view it" ,
    "the_map_has_arg_world_processors_arg_instruction_lines_and_arg_characters" to "The map has @ world processors, @ instruction lines, and @ characters." ,
    "there_are_no_enemies_in_this_wave" to "There are no enemies in this wave" ,
    "there_are_too_many_buildings_to_avoid_lag_and_only_keep_the_first_1000_plans" to "[yellow]There are too many buildings to avoid lag and only keep the first 1000 plans." ,
    "this_is_a_cheat_feature_njump_to_the" to "[red]This is a cheat feature[]\\nJump to the target wave instantly (without spawning enemies)" ,
    "this_is_a_message_from_mdtx" to "This is a message from MDTX-" ,
    "tiles" to "tiles" ,
    "tip_all_schematics_containing_processors" to "TIP: All schematics containing processors" ,
    "toggle" to "Toggle" ,
    "toggle_your_team_s_cheat" to "Toggle your team's Cheat" ,
    "total_arg_arg_arg_arg_tile_radius" to "Total @@@~@ tile radius" ,
    "ui_icon_library" to "UI Icon Library" ,
    "ui_toolkit" to "UI Toolkit" ,
    "unique" to "Unique" ,
    "unit" to "Unit:" ,
    "unit_factory" to "Unit Factory" ,
    "unit_factory_x" to "Unit Factory-X" ,
    "unit_rendering" to "Unit Rendering" ,
    "unlimited" to "Unlimited" ,
    "unlock" to "Unlock" ,
    "unlock_and_allow_all_blocks" to "Unlock and allow all blocks" ,
    "updated_edited_logic" to "[orange]Updated edited logic!" ,
    "upload_failed_try_again" to "Upload failed, try again?" ,
    "vanilla" to "Vanilla" ,
    "view_recording_info" to "View recording info" ,
    "wall_shadow_rendering" to "Wall Shadow Rendering" ,
    "warning_image_may_be_too_large_please_try_compressing_image" to "[orange]Warning: Image may be too large, please try compressing image" ,
    "wave" to "Wave" ,
    "wave_in_prefix" to "in" ,
    "wave_info" to "Wave Info" ,
    "wave_settings" to "Wave Settings" ,
    "waves" to "Waves:" ,
    "waves_suffix" to "waves," ,
    "x_scan_speed" to "x scan speed" ,
    "you_are_already_on_the_latest_version" to "You are already on the latest version." ,
    "you_were_poked_please_pay_attention_to_the_information_box" to "[orange]You were poked. Please check the message dialog." ,
    "zoom" to "Zoom" ,
    "zoom_x" to "Zoom: x" ,
    "zoom_zoom" to "Zoom: " ,
)

private fun currentUiTexts(): Map<String, String> =
    if(Core.bundle.locale.language == Locale.CHINESE.language) uiTextsZh else uiTextsEn

fun ui(key: String): String = currentUiTexts()[key] ?: key

fun uiTemplate(key: String, vararg args: Any?): String {
    var text = ui("template.$key")
    args.forEachIndexed { index, arg ->
        text = text.replace("{$index}", arg?.toString() ?: "null")
    }
    return text
}

fun uiJavaWarnLog(javaVersion: String): String = uiTemplate("javaWarnLog", javaVersion)
fun uiJavaWarnDialog(javaVersion: String): String = uiTemplate("javaWarnDialog", javaVersion)
fun uiWindowTitle(version: String, enabledMods: Int, totalMods: Int, width: Int, height: Int): String =
    uiTemplate("windowTitle", version, enabledMods, totalMods) + " | " + width + "x" + height

fun uiArcMessageCenter(): String = ui("arc_message_center")
fun uiMaxChatHistoryHint(): String = ui("maximum_storage_of_chat_history_too_high_may_cause_lag")
fun uiChatHistoryCleanupHint(): String = ui("chat_history_exceeding_the_limit_will_be_cleared_when_loading_the_map")
fun uiClear(): String = ui("clear")
fun uiExport(): String = ui("export")
fun uiExportChatHistory(): String = ui("export_chat_history")
fun uiLoadMap(mapName: String): String = uiTemplate("loadMap", mapName)
fun uiIntroduction(description: String): String = uiTemplate("introduction", description)
fun uiWaveEvent(wave: Int, detail: String): String = uiTemplate("waveEvent", wave, detail)
fun uiCopiedChatRecord(): String = ui("copied_this_chat_record")
fun uiExportHeader(version: String): String = uiTemplate("exportHeader", version)
fun uiExportMap(mapName: String, mode: String): String = uiTemplate("exportMap", mapName, mode)
fun uiCurrentWave(wave: Int): String = uiTemplate("currentWave", wave)
fun uiExportCount(count: Int): String = uiTemplate("exportCount", count)
fun uiChatType(): String = ui("chat")
fun uiServerMsgType(): String = ui("server_msg")
fun uiMarkCoordinatesType(): String = ui("mark_coordinates")
fun uiMarkPlayerType(): String = ui("mark_player")
fun uiCommandType(): String = ui("command")
fun uiLogicNoticeType(): String = ui("logic_notice")
fun uiLogicAnnouncementType(): String = ui("logic_announcement")
fun uiEventMapLoadType(): String = ui("event_map_load")
fun uiEventWaveType(): String = ui("event_wave")

fun uiLogicHelperX(): String = ui("logic_helper_x")
fun uiHideLogicHelper(): String = ui("hide_logic_helper")
fun uiUpdatedEditedLogic(): String = ui("updated_edited_logic")
fun uiRefreshEditedLogic(): String = ui("refresh_edited_logic")
fun uiOn(): String = ui("on")
fun uiOff(): String = ui("off")
fun uiToggleState(label: String, state: String): String = uiTemplate("toggleState", label, state)
fun uiFlashOnChange(): String = ui("flash_on_change")
fun uiFlashOnVariableChange(): String = ui("flash_on_variable_change")
fun uiAutoRefreshVariables(): String = ui("auto_refresh_variables")
fun uiAutoRefreshVariablesHint(): String = ui("automatically_refresh_variables")
fun uiPaused(): String = ui("paused")
fun uiGameResumed(): String = ui("game_resumed")
fun uiPauseLogicGameExecution(): String = ui("pause_logic_game_execution")
fun uiRefreshInterval(): String = ui("refresh_interval")
fun uiCopiedVariableNameHint(): String = ui("copied_variable_name_n_arg")
fun uiCopiedVariableAttributesHint(): String = ui("copied_variable_attributes_n_arg")
fun uiCopiedPrintBufferHint(): String = ui("copied_print_buffer_n_arg")
fun uiCopiedMemory(value: Double): String = uiTemplate("copiedMemory", value)
fun uiNoPermissionToEditViewOnly(): String = ui("no_permission_to_edit_view_only")
fun uiResetAllLinks(): String = ui("reset_all_links")
fun uiExtractCodeFromSchematic(): String = ui("extract_code_from_schematic")
fun uiSelectCode(): String = ui("select_code")
fun uiTipAllSchematicsContainingProcessors(): String = ui("tip_all_schematics_containing_processors")

fun uiBasic(): String = ui("basic")
fun uiSquared(): String = ui("squared")
fun uiArcImageConverter(): String = ui("arc_image_converter")
fun uiSelectAndImportPictures(): String = ui("select_and_import_pictures_which_can_be_converted")
fun uiSelectImagePng(): String = ui("select_image_png")
fun uiWarnImageTooLarge(): String = ui("warning_image_may_be_too_large_please_try_compressing_image")
fun uiFailedReadImage(error: Any?): String = uiTemplate("failedReadImage", error)
fun uiAutomaticallySaveAsBlueprint(): String = ui("automatically_save_as_blueprint")
fun uiZoomZoom(): String = ui("zoom_zoom")
fun uiHueMode(): String = ui("hue_mode")
fun uiLabelWithEmoji(label: String, emoji: String): String = uiTemplate("labelWithEmoji", label, emoji)
fun uiLogicArtWebsite(): String = ui("logic_art_website")
fun uiPath(): String = ui("path")
fun uiName(): String = ui("name")
fun uiOriginalSize(): String = ui("original_size")
fun uiScaledSize(): String = ui("scaled_size")
fun uiCanvas(): String = ui("canvas")
fun uiArtboard(): String = ui("artboard")
fun uiPixelArt(): String = ui("pixel_art")
fun uiSize(): String = ui("size")
fun uiSavedBlueprint(name: String): String = uiTemplate("savedBlueprint", name)
