@file:JvmName("FuncX")
@file:JvmMultifileClass

package mindustryX.features.func

import arc.Core

private fun ui(key: String): String = Core.bundle.get("mdtx.ui.$key")
private fun uiTemplate(key: String, vararg args: Any?): String = Core.bundle.format("mdtx.ui.template.$key", *args)

fun uiJavaWarnLog(javaVersion: String): String = uiTemplate("javaWarnLog", javaVersion)
fun uiJavaWarnDialog(javaVersion: String): String = uiTemplate("javaWarnDialog", javaVersion)
fun uiWindowTitle(version: String, enabledMods: Int, totalMods: Int, width: Int, height: Int): String =
    uiTemplate("windowTitle", version, enabledMods, totalMods) + " | " + width + "x" + height

fun uiArcMessageCenter(): String = ui("arc_message_center")
fun uiMaxChatHistoryHint(): String = ui("maximum_storage_of_chat_history_too_high_may_cause_lag")
fun uiChatHistoryCleanupHint(): String = ui("chat_history_exceeding_the_limit_will_be_cleared_when_loading_the_map")
fun uiClear(): String = ui("clear")
fun uiExport(): String = ui("export")
fun uiExportChatHistory(): String = ui("export_chat_history")
fun uiLoadMap(mapName: String): String = uiTemplate("loadMap", mapName)
fun uiIntroduction(description: String): String = uiTemplate("introduction", description)
fun uiWaveEvent(wave: Int, detail: String): String = uiTemplate("waveEvent", wave, detail)
fun uiCopiedChatRecord(): String = ui("copied_this_chat_record")
fun uiExportHeader(version: String): String = uiTemplate("exportHeader", version)
fun uiExportMap(mapName: String, mode: String): String = uiTemplate("exportMap", mapName, mode)
fun uiCurrentWave(wave: Int): String = uiTemplate("currentWave", wave)
fun uiExportCount(count: Int): String = uiTemplate("exportCount", count)
fun uiChatType(): String = ui("chat")
fun uiServerMsgType(): String = ui("server_msg")
fun uiMarkCoordinatesType(): String = ui("mark_coordinates")
fun uiMarkPlayerType(): String = ui("mark_player")
fun uiCommandType(): String = ui("command")
fun uiLogicNoticeType(): String = ui("logic_notice")
fun uiLogicAnnouncementType(): String = ui("logic_announcement")
fun uiEventMapLoadType(): String = ui("event_map_load")
fun uiEventWaveType(): String = ui("event_wave")

fun uiLogicHelperX(): String = ui("logic_helper_x")
fun uiHideLogicHelper(): String = ui("hide_logic_helper")
fun uiUpdatedEditedLogic(): String = ui("updated_edited_logic")
fun uiRefreshEditedLogic(): String = ui("refresh_edited_logic")
fun uiOn(): String = ui("on")
fun uiOff(): String = ui("off")
fun uiToggleState(label: String, state: String): String = uiTemplate("toggleState", label, state)
fun uiFlashOnChange(): String = ui("flash_on_change")
fun uiFlashOnVariableChange(): String = ui("flash_on_variable_change")
fun uiAutoRefreshVariables(): String = ui("auto_refresh_variables")
fun uiAutoRefreshVariablesHint(): String = ui("automatically_refresh_variables")
fun uiPaused(): String = ui("paused")
fun uiGameResumed(): String = ui("game_resumed")
fun uiPauseLogicGameExecution(): String = ui("pause_logic_game_execution")
fun uiRefreshInterval(): String = ui("refresh_interval")
fun uiCopiedVariableNameHint(): String = ui("copied_variable_name_n_arg")
fun uiCopiedVariableAttributesHint(): String = ui("copied_variable_attributes_n_arg")
fun uiCopiedPrintBufferHint(): String = ui("copied_print_buffer_n_arg")
fun uiCopiedMemory(value: Double): String = uiTemplate("copiedMemory", value)
fun uiNoPermissionToEditViewOnly(): String = ui("no_permission_to_edit_view_only")
fun uiResetAllLinks(): String = ui("reset_all_links")
fun uiExtractCodeFromSchematic(): String = ui("extract_code_from_schematic")
fun uiSelectCode(): String = ui("select_code")
fun uiTipAllSchematicsContainingProcessors(): String = ui("tip_all_schematics_containing_processors")

fun uiBasic(): String = ui("basic")
fun uiSquared(): String = ui("squared")
fun uiArcImageConverter(): String = ui("arc_image_converter")
fun uiSelectAndImportPictures(): String = ui("select_and_import_pictures_which_can_be_converted")
fun uiSelectImagePng(): String = ui("select_image_png")
fun uiWarnImageTooLarge(): String = ui("warning_image_may_be_too_large_please_try_compressing_image")
fun uiFailedReadImage(error: Any?): String = uiTemplate("failedReadImage", error)
fun uiAutomaticallySaveAsBlueprint(): String = ui("automatically_save_as_blueprint")
fun uiZoomZoom(): String = ui("zoom_zoom")
fun uiHueMode(): String = ui("hue_mode")
fun uiLabelWithEmoji(label: String, emoji: String): String = uiTemplate("labelWithEmoji", label, emoji)
fun uiLogicArtWebsite(): String = ui("logic_art_website")
fun uiPath(): String = ui("path")
fun uiName(): String = ui("name")
fun uiOriginalSize(): String = ui("original_size")
fun uiScaledSize(): String = ui("scaled_size")
fun uiCanvas(): String = ui("canvas")
fun uiArtboard(): String = ui("artboard")
fun uiPixelArt(): String = ui("pixel_art")
fun uiSize(): String = ui("size")
fun uiSavedBlueprint(name: String): String = uiTemplate("savedBlueprint", name)
